# Generated by Django 3.2.4 on 2022-01-14 14:18

import django.db.models.deletion
from django.db import migrations, models

import webmentions_tester.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mentions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("submission_time", models.DateTimeField(auto_now_add=True)),
                (
                    "expiration_time",
                    models.DateTimeField(
                        default=webmentions_tester.models._expiration_time
                    ),
                ),
                (
                    "outgoing_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentions.outgoingwebmentionstatus",
                    ),
                ),
            ],
        ),
    ]
