// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, type Options as Options2, type RequestResult, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { ContactApiSendMailData, ContactApiSendMailErrors, ContactApiSendMailResponses, GithubApiGetGithubEventsData, GithubApiGetGithubEventsResponses, MainApiGlobalStateGetGlobalStateData, MainApiGlobalStateGetGlobalStateResponses, MainApiPostsAboutData, MainApiPostsAboutResponses, MainApiPostsAboutRootData, MainApiPostsAboutRootResponses, MainApiPostsAppData, MainApiPostsAppResponses, MainApiPostsChangelogData, MainApiPostsChangelogResponses, MainApiPostsPostData, MainApiPostsPostFeedData, MainApiPostsPostFeedResponses, MainApiPostsPostResponses, MainApiStatusCheckRedirectData, MainApiStatusCheckRedirectResponses, MainApiStatusPing2Data, MainApiStatusPing2Responses, MainApiStatusPingData, MainApiStatusPingResponses, MainApiStatusWhoamiData, MainApiStatusWhoamiResponses, MainApiTagsTagsData, MainApiTagsTagsResponses, WebmentionsTesterApiGetTemporaryWebmentionsData, WebmentionsTesterApiGetTemporaryWebmentionsResponses, WebmentionsTesterApiPostWebmentionData, WebmentionsTesterApiPostWebmentionResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Post
 */
export const mainApiPostsPost = <ThrowOnError extends boolean = false>(options: Options<MainApiPostsPostData, ThrowOnError>): RequestResult<MainApiPostsPostResponses, unknown, ThrowOnError> => (options.client ?? client).get<MainApiPostsPostResponses, unknown, ThrowOnError>({ url: '/api/posts/{slug}/', ...options });

/**
 * App
 */
export const mainApiPostsApp = <ThrowOnError extends boolean = false>(options: Options<MainApiPostsAppData, ThrowOnError>): RequestResult<MainApiPostsAppResponses, unknown, ThrowOnError> => (options.client ?? client).get<MainApiPostsAppResponses, unknown, ThrowOnError>({ url: '/api/apps/{slug}/', ...options });

/**
 * Changelog
 */
export const mainApiPostsChangelog = <ThrowOnError extends boolean = false>(options: Options<MainApiPostsChangelogData, ThrowOnError>): RequestResult<MainApiPostsChangelogResponses, unknown, ThrowOnError> => (options.client ?? client).get<MainApiPostsChangelogResponses, unknown, ThrowOnError>({ url: '/api/changelog/{slug}/', ...options });

/**
 * About Root
 */
export const mainApiPostsAboutRoot = <ThrowOnError extends boolean = false>(options?: Options<MainApiPostsAboutRootData, ThrowOnError>): RequestResult<MainApiPostsAboutRootResponses, unknown, ThrowOnError> => (options?.client ?? client).get<MainApiPostsAboutRootResponses, unknown, ThrowOnError>({ url: '/api/about/', ...options });

/**
 * About
 */
export const mainApiPostsAbout = <ThrowOnError extends boolean = false>(options: Options<MainApiPostsAboutData, ThrowOnError>): RequestResult<MainApiPostsAboutResponses, unknown, ThrowOnError> => (options.client ?? client).get<MainApiPostsAboutResponses, unknown, ThrowOnError>({ url: '/api/about/{path}', ...options });

/**
 * Post Feed
 */
export const mainApiPostsPostFeed = <ThrowOnError extends boolean = false>(options?: Options<MainApiPostsPostFeedData, ThrowOnError>): RequestResult<MainApiPostsPostFeedResponses, unknown, ThrowOnError> => (options?.client ?? client).get<MainApiPostsPostFeedResponses, unknown, ThrowOnError>({ url: '/api/posts/', ...options });

/**
 * Ping
 */
export const mainApiStatusPing = <ThrowOnError extends boolean = false>(options?: Options<MainApiStatusPingData, ThrowOnError>): RequestResult<MainApiStatusPingResponses, unknown, ThrowOnError> => (options?.client ?? client).get<MainApiStatusPingResponses, unknown, ThrowOnError>({ url: '/api/ping/', ...options });

/**
 * Ping
 */
export const mainApiStatusPing2 = <ThrowOnError extends boolean = false>(options?: Options<MainApiStatusPing2Data, ThrowOnError>): RequestResult<MainApiStatusPing2Responses, unknown, ThrowOnError> => (options?.client ?? client).head<MainApiStatusPing2Responses, unknown, ThrowOnError>({ url: '/api/ping/', ...options });

/**
 * Whoami
 */
export const mainApiStatusWhoami = <ThrowOnError extends boolean = false>(options?: Options<MainApiStatusWhoamiData, ThrowOnError>): RequestResult<MainApiStatusWhoamiResponses, unknown, ThrowOnError> => (options?.client ?? client).get<MainApiStatusWhoamiResponses, unknown, ThrowOnError>({ url: '/api/whoami/', ...options });

/**
 * Check Redirect
 */
export const mainApiStatusCheckRedirect = <ThrowOnError extends boolean = false>(options: Options<MainApiStatusCheckRedirectData, ThrowOnError>): RequestResult<MainApiStatusCheckRedirectResponses, unknown, ThrowOnError> => (options.client ?? client).get<MainApiStatusCheckRedirectResponses, unknown, ThrowOnError>({ url: '/api/redirect/', ...options });

/**
 * Get Global State
 */
export const mainApiGlobalStateGetGlobalState = <ThrowOnError extends boolean = false>(options?: Options<MainApiGlobalStateGetGlobalStateData, ThrowOnError>): RequestResult<MainApiGlobalStateGetGlobalStateResponses, unknown, ThrowOnError> => (options?.client ?? client).get<MainApiGlobalStateGetGlobalStateResponses, unknown, ThrowOnError>({ url: '/api/state/', ...options });

/**
 * Tags
 */
export const mainApiTagsTags = <ThrowOnError extends boolean = false>(options?: Options<MainApiTagsTagsData, ThrowOnError>): RequestResult<MainApiTagsTagsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<MainApiTagsTagsResponses, unknown, ThrowOnError>({ url: '/api/tags/', ...options });

/**
 * Send Mail
 */
export const contactApiSendMail = <ThrowOnError extends boolean = false>(options: Options<ContactApiSendMailData, ThrowOnError>): RequestResult<ContactApiSendMailResponses, ContactApiSendMailErrors, ThrowOnError> => (options.client ?? client).post<ContactApiSendMailResponses, ContactApiSendMailErrors, ThrowOnError>({
  url: '/api/contact/',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * Get Temporary Webmentions
 */
export const webmentionsTesterApiGetTemporaryWebmentions = <ThrowOnError extends boolean = false>(options: Options<WebmentionsTesterApiGetTemporaryWebmentionsData, ThrowOnError>): RequestResult<WebmentionsTesterApiGetTemporaryWebmentionsResponses, unknown, ThrowOnError> => (options.client ?? client).get<WebmentionsTesterApiGetTemporaryWebmentionsResponses, unknown, ThrowOnError>({ url: '/api/webmentions_tester/', ...options });

/**
 * Post Webmention
 */
export const webmentionsTesterApiPostWebmention = <ThrowOnError extends boolean = false>(options: Options<WebmentionsTesterApiPostWebmentionData, ThrowOnError>): RequestResult<WebmentionsTesterApiPostWebmentionResponses, unknown, ThrowOnError> => (options.client ?? client).post<WebmentionsTesterApiPostWebmentionResponses, unknown, ThrowOnError>({
  ...urlSearchParamsBodySerializer,
  url: '/api/webmentions_tester/',
  ...options,
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded',
    ...options.headers
  }
});

/**
 * Get Github Events
 */
export const githubApiGetGithubEvents = <ThrowOnError extends boolean = false>(options?: Options<GithubApiGetGithubEventsData, ThrowOnError>): RequestResult<GithubApiGetGithubEventsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GithubApiGetGithubEventsResponses, unknown, ThrowOnError>({ url: '/api/github/recent/', ...options });
