// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: string;
};

/**
 * File
 */
export type File = {
  url: Url;
  thumbnail_url?: Url;
  type: MediaType;
  name?: PlainText | null;
  description: PlainText | null;
  fit: ImageFit | null;
  /**
   * Is Nsfw
   */
  is_nsfw: boolean;
  /**
   * Aspect Ratio
   */
  aspect_ratio: number | null;
  /**
   * Duration Seconds
   */
  duration_seconds: number | null;
};

/**
 * HCard
 */
export type HCard = {
  /**
   * Name
   */
  name: string | null;
  /**
   * Avatar
   */
  avatar?: string | null;
  /**
   * Homepage
   */
  homepage: string | null;
};

export type HexColor = string;

/**
 * ImageFit
 */
export type ImageFit = 'cover' | 'contain';

/**
 * IncomingMentionType
 *
 * Properties that describe the context of the incoming webmention.
 *
 * See: https://microformats.org/wiki/h-entry
 */
export type IncomingMentionType = 'u-bookmark-of' | 'u-like-of' | 'u-listen-of' | 'u-in-reply-to' | 'u-repost-of' | 'u-translation-of' | 'u-watch-of';

/**
 * Link
 */
export type Link = {
  url: Url;
  label?: PlainText | null;
  description?: PlainText | null;
  icon?: Url | null;
};

/**
 * MediaType
 */
export type MediaType = 'audio' | 'video' | 'image' | 'text' | 'unknown';

/**
 * Mention
 */
export type Mention = {
  /**
   * Source Url
   */
  source_url: string;
  hcard: HCard | null;
  /**
   * Quote
   */
  quote: string | null;
  /**
   * Type
   */
  type?: IncomingMentionType | string | null;
  /**
   * Date
   */
  date: string;
};

export type PlainText = string;

/**
 * PostDetail
 */
export type PostDetail = {
  /**
   * Post Type
   */
  post_type?: 'post';
  title: PlainText | null;
  url: Url;
  /**
   * Is Published
   */
  is_published: boolean;
  /**
   * Published At
   */
  published_at: string;
  theme?: Theme | null;
  hero_embedded_url: Url | null;
  hero_image: File | null;
  content_html: UnsafeHtml | null;
  content_script: UnsafeHtml | null;
  /**
   * Files
   */
  files: Array<File>;
  subtitle?: PlainText | null;
  hero_html: UnsafeHtml | null;
  /**
   * Links
   */
  links: Array<Link>;
  /**
   * Tags
   */
  tags: Array<Tag>;
  /**
   * Mentions
   */
  mentions: Array<Mention>;
};

/**
 * Tag
 */
export type Tag = {
  name: PlainText;
};

/**
 * Theme
 */
export type Theme = {
  muted?: HexColor | null;
  vibrant?: HexColor | null;
};

export type UnsafeHtml = string;

export type Url = string;

/**
 * AppDetail
 */
export type AppDetail = {
  /**
   * Post Type
   */
  post_type?: 'app';
  title: PlainText | null;
  url: Url;
  /**
   * Is Published
   */
  is_published: boolean;
  /**
   * Published At
   */
  published_at: string;
  theme?: Theme | null;
  hero_embedded_url: Url | null;
  hero_image: File | null;
  content_html: UnsafeHtml | null;
  content_script: UnsafeHtml | null;
  /**
   * Files
   */
  files: Array<File>;
  subtitle?: PlainText | null;
  hero_html: UnsafeHtml | null;
  /**
   * Links
   */
  links: Array<Link>;
  /**
   * Tags
   */
  tags: Array<Tag>;
  /**
   * Mentions
   */
  mentions: Array<Mention>;
  /**
   * Changelog
   */
  changelog: Array<ChangelogDetail>;
  icon: File | null;
  script?: Url | null;
  script_html: UnsafeHtml | null;
  /**
   * Is Widget
   */
  is_widget: boolean;
  widget_data: UrlSearchParams | null;
  widget_style: HtmlAttribute | null;
};

/**
 * AppPreview
 */
export type AppPreview = {
  /**
   * Post Type
   */
  post_type?: 'app';
  title: PlainText | null;
  url: Url;
  /**
   * Is Published
   */
  is_published: boolean;
  /**
   * Published At
   */
  published_at: string;
  theme?: Theme | null;
  hero_embedded_url: Url | null;
  hero_image: File | null;
  content_html: UnsafeHtml | null;
  content_script: UnsafeHtml | null;
  /**
   * Files
   */
  files: Array<File>;
  /**
   * Is Preview
   */
  is_preview: boolean;
  icon?: File | null;
};

/**
 * ChangelogDetail
 */
export type ChangelogDetail = {
  /**
   * Post Type
   */
  post_type?: 'changelog';
  title: PlainText | null;
  url: Url;
  /**
   * Is Published
   */
  is_published: boolean;
  /**
   * Published At
   */
  published_at: string;
  theme?: Theme | null;
  hero_embedded_url: Url | null;
  hero_image: File | null;
  content_html: UnsafeHtml | null;
  content_script: UnsafeHtml | null;
  /**
   * Files
   */
  files: Array<File>;
  subtitle?: PlainText | null;
  hero_html: UnsafeHtml | null;
  /**
   * Links
   */
  links: Array<Link>;
  /**
   * Tags
   */
  tags: Array<Tag>;
  /**
   * Mentions
   */
  mentions: Array<Mention>;
  app: AppPreview;
  version: PlainText;
};

export type HtmlAttribute = string;

export type UrlSearchParams = string;

/**
 * AboutDetail
 */
export type AboutDetail = {
  /**
   * Post Type
   */
  post_type?: 'about';
  title: PlainText | null;
  url: Url;
  /**
   * Is Published
   */
  is_published: boolean;
  /**
   * Published At
   */
  published_at: string;
  theme?: Theme | null;
  hero_embedded_url: Url | null;
  hero_image: File | null;
  content_html: UnsafeHtml | null;
  content_script: UnsafeHtml | null;
  /**
   * Files
   */
  files: Array<File>;
  subtitle?: PlainText | null;
  hero_html: UnsafeHtml | null;
  /**
   * Links
   */
  links: Array<Link>;
  /**
   * Tags
   */
  tags: Array<Tag>;
  /**
   * Mentions
   */
  mentions: Array<Mention>;
  /**
   * Path
   */
  path: string;
  parent: AboutPreview | null;
  /**
   * Siblings
   */
  siblings: Array<AboutPreview>;
  /**
   * Children
   */
  children: Array<AboutPreview>;
};

/**
 * AboutPreview
 */
export type AboutPreview = {
  /**
   * Post Type
   */
  post_type?: 'about';
  title: PlainText | null;
  url: Url;
  /**
   * Is Published
   */
  is_published: boolean;
  /**
   * Published At
   */
  published_at: string;
  theme?: Theme | null;
  hero_embedded_url: Url | null;
  hero_image: File | null;
  content_html: UnsafeHtml | null;
  content_script: UnsafeHtml | null;
  /**
   * Files
   */
  files: Array<File>;
  /**
   * Is Preview
   */
  is_preview: boolean;
  /**
   * Path
   */
  path: string;
};

/**
 * Input
 */
export type Input = {
  /**
   * Limit
   */
  limit?: number;
  /**
   * Offset
   */
  offset?: number;
};

/**
 * PagedPostPreview
 */
export type PagedPostPreview = {
  /**
   * Items
   */
  items: Array<PostPreview>;
  /**
   * Count
   */
  count: number;
  /**
   * Page Size
   */
  page_size: number;
  /**
   * Previous
   */
  previous: number | null;
  /**
   * Next
   */
  next: number | null;
};

/**
 * PostPreview
 */
export type PostPreview = {
  post_type: PostType;
  title: PlainText | null;
  url: Url;
  /**
   * Is Published
   */
  is_published: boolean;
  /**
   * Published At
   */
  published_at: string;
  theme?: Theme | null;
  hero_embedded_url: Url | null;
  hero_image: File | null;
  content_html: UnsafeHtml | null;
  content_script: UnsafeHtml | null;
  /**
   * Files
   */
  files: Array<File>;
  /**
   * Is Preview
   */
  is_preview: boolean;
};

export type PostType = 'post' | 'app' | 'changelog' | 'about';

/**
 * WhoAmiISchema
 */
export type WhoAmiISchema = {
  /**
   * Ip
   */
  ip: string;
  /**
   * Device
   */
  device: string;
  /**
   * Os
   */
  os: string;
  /**
   * Browser
   */
  browser: string;
};

/**
 * RedirectSchema
 */
export type RedirectSchema = {
  /**
   * Redirect
   */
  redirect: string;
};

/**
 * FeedSchema
 */
export type FeedSchema = {
  /**
   * Name
   */
  name: string;
  /**
   * Slug
   */
  slug: string;
  /**
   * Description
   */
  description: string | null;
};

/**
 * GlobalHCard
 */
export type GlobalHCard = {
  /**
   * Name
   */
  name: string;
  /**
   * Url
   */
  url: string;
  photo: File | null;
  logo: File | null;
  location: HAdr | null;
  /**
   * Birthday
   */
  birthday: string | null;
  /**
   * Relme
   */
  relme: Array<Link>;
};

/**
 * GlobalState
 */
export type GlobalState = {
  /**
   * Motd
   */
  motd: string | null;
  hcard: GlobalHCard | null;
  /**
   * Poi
   */
  poi: Array<Link>;
  /**
   * Feeds
   */
  feeds: Array<FeedSchema>;
};

/**
 * HAdr
 */
export type HAdr = {
  /**
   * Locality
   */
  locality: string | null;
  /**
   * Region
   */
  region: string | null;
  /**
   * Country
   */
  country: string | null;
};

/**
 * TagDetail
 */
export type TagDetail = {
  /**
   * Name
   */
  name: string;
  /**
   * Count
   */
  count: number;
};

/**
 * ContactForm
 */
export type ContactForm = {
  /**
   * Name
   */
  name: string;
  /**
   * Contact Info
   */
  contact_info: string;
  /**
   * Message
   */
  message: string;
  /**
   * Recaptcha Token
   */
  recaptcha_token: string;
};

/**
 * TempMention
 */
export type TempMention = {
  /**
   * Url
   */
  url: string;
  /**
   * Submitted At
   */
  submitted_at: string;
  /**
   * Expires At
   */
  expires_at: string;
  status: TempMentionStatus | null;
};

/**
 * TempMentionStatus
 */
export type TempMentionStatus = {
  /**
   * Successful
   */
  successful: boolean;
  /**
   * Status Code
   */
  status_code: number;
  /**
   * Message
   */
  message: string;
  /**
   * Source Url
   */
  source_url: string;
  /**
   * Target Url
   */
  target_url: string;
  /**
   * Endpoint
   */
  endpoint: string | null;
};

/**
 * WebmentionTesterSchema
 */
export type WebmentionTesterSchema = {
  /**
   * Temporary Outgoing Mentions
   */
  temporary_outgoing_mentions: Array<TempMention>;
  /**
   * Mentions
   */
  mentions: Array<Mention>;
};

/**
 * GithubCommit
 */
export type GithubCommit = {
  /**
   * Sha
   */
  sha: string;
  /**
   * Message
   */
  message: string;
  /**
   * Url
   */
  url: string;
};

/**
 * GithubCreateEventPayload
 */
export type GithubCreateEventPayload = {
  /**
   * Ref Type
   */
  ref_type: 'branch' | 'tag' | 'repository';
  /**
   * Ref
   */
  ref: string | null;
};

/**
 * GithubIssueEventPayload
 */
export type GithubIssueEventPayload = {
  /**
   * Number
   */
  number: number;
  /**
   * Url
   */
  url: string;
  /**
   * Closed At
   */
  closed_at: string;
};

/**
 * GithubPrivateEvent
 */
export type GithubPrivateEvent = {
  /**
   * Type
   */
  type: 'PrivateEventSummary';
  /**
   * Created At
   */
  created_at: string;
  /**
   * Event Count
   */
  event_count: number;
  /**
   * Change Count
   */
  change_count: number;
  /**
   * Repository Count
   */
  repository_count: number;
};

/**
 * GithubPublicCreateEvent
 */
export type GithubPublicCreateEvent = {
  /**
   * Type
   */
  type: 'CreateEvent';
  /**
   * Created At
   */
  created_at: string;
  /**
   * Id
   */
  id: number;
  repository: GithubRepositorySchema;
  payload: GithubCreateEventPayload;
};

/**
 * GithubPublicIssueEvent
 */
export type GithubPublicIssueEvent = {
  /**
   * Type
   */
  type: 'IssuesEvent';
  /**
   * Created At
   */
  created_at: string;
  /**
   * Id
   */
  id: number;
  repository: GithubRepositorySchema;
  payload: GithubIssueEventPayload;
};

/**
 * GithubPublicPullRequestEvent
 */
export type GithubPublicPullRequestEvent = {
  /**
   * Type
   */
  type: 'PullRequestEvent';
  /**
   * Created At
   */
  created_at: string;
  /**
   * Id
   */
  id: number;
  repository: GithubRepositorySchema;
  payload: GithubPullRequestPayload;
};

/**
 * GithubPublicPushEvent
 */
export type GithubPublicPushEvent = {
  /**
   * Type
   */
  type: 'PushEvent';
  /**
   * Created At
   */
  created_at: string;
  /**
   * Id
   */
  id: number;
  repository: GithubRepositorySchema;
  /**
   * Payload
   */
  payload: Array<GithubCommit>;
};

/**
 * GithubPublicReleaseEvent
 */
export type GithubPublicReleaseEvent = {
  /**
   * Type
   */
  type: 'ReleaseEvent';
  /**
   * Created At
   */
  created_at: string;
  /**
   * Id
   */
  id: number;
  repository: GithubRepositorySchema;
  payload: GithubReleasePayload;
};

/**
 * GithubPublicWikiEvent
 */
export type GithubPublicWikiEvent = {
  /**
   * Type
   */
  type: 'GollumEvent';
  /**
   * Created At
   */
  created_at: string;
  /**
   * Id
   */
  id: number;
  repository: GithubRepositorySchema;
  /**
   * Payload
   */
  payload: Array<GithubWikiEdit>;
};

/**
 * GithubPullRequestPayload
 */
export type GithubPullRequestPayload = {
  /**
   * Number
   */
  number: number;
  /**
   * Url
   */
  url: string;
  /**
   * Merged At
   */
  merged_at: string;
  /**
   * Additions Count
   */
  additions_count: number;
  /**
   * Deletions Count
   */
  deletions_count: number;
  /**
   * Changed Files Count
   */
  changed_files_count: number;
};

/**
 * GithubRecentEvents
 */
export type GithubRecentEvents = {
  /**
   * Events
   */
  events: Array<GithubPrivateEvent | GithubPublicCreateEvent | GithubPublicIssueEvent | GithubPublicPullRequestEvent | GithubPublicReleaseEvent | GithubPublicPushEvent | GithubPublicWikiEvent>;
};

/**
 * GithubReleasePayload
 */
export type GithubReleasePayload = {
  /**
   * Name
   */
  name: string;
  /**
   * Url
   */
  url: string;
  /**
   * Description
   */
  description: string;
  /**
   * Published At
   */
  published_at: string;
};

/**
 * GithubRepositorySchema
 */
export type GithubRepositorySchema = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Url
   */
  url: string;
  /**
   * License
   */
  license: string | null;
  /**
   * Description
   */
  description: string | null;
};

/**
 * GithubWikiEdit
 */
export type GithubWikiEdit = {
  /**
   * Name
   */
  name: string;
  /**
   * Url
   */
  url: string;
  /**
   * Action
   */
  action: 'created' | 'edited';
};

export type MainApiPostsPostData = {
  body?: never;
  path: {
    /**
     * Slug
     */
    slug: string;
  };
  query?: never;
  url: '/api/posts/{slug}/';
};

export type MainApiPostsPostResponses = {
  /**
   * OK
   */
  200: PostDetail;
};

export type MainApiPostsPostResponse = MainApiPostsPostResponses[keyof MainApiPostsPostResponses];

export type MainApiPostsAppData = {
  body?: never;
  path: {
    /**
     * Slug
     */
    slug: string;
  };
  query?: never;
  url: '/api/apps/{slug}/';
};

export type MainApiPostsAppResponses = {
  /**
   * OK
   */
  200: AppDetail;
};

export type MainApiPostsAppResponse = MainApiPostsAppResponses[keyof MainApiPostsAppResponses];

export type MainApiPostsChangelogData = {
  body?: never;
  path: {
    /**
     * Slug
     */
    slug: string;
  };
  query?: never;
  url: '/api/changelog/{slug}/';
};

export type MainApiPostsChangelogResponses = {
  /**
   * OK
   */
  200: ChangelogDetail;
};

export type MainApiPostsChangelogResponse = MainApiPostsChangelogResponses[keyof MainApiPostsChangelogResponses];

export type MainApiPostsAboutRootData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/about/';
};

export type MainApiPostsAboutRootResponses = {
  /**
   * OK
   */
  200: AboutDetail;
};

export type MainApiPostsAboutRootResponse = MainApiPostsAboutRootResponses[keyof MainApiPostsAboutRootResponses];

export type MainApiPostsAboutData = {
  body?: never;
  path: {
    /**
     * Path
     */
    path: string;
  };
  query?: never;
  url: '/api/about/{path}';
};

export type MainApiPostsAboutResponses = {
  /**
   * OK
   */
  200: AboutDetail;
};

export type MainApiPostsAboutResponse = MainApiPostsAboutResponses[keyof MainApiPostsAboutResponses];

export type MainApiPostsPostFeedData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Query
     */
    query?: string | null;
    /**
     * Tag
     */
    tag?: string | null;
    /**
     * Feed
     */
    feed?: string | null;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Offset
     */
    offset?: number;
  };
  url: '/api/posts/';
};

export type MainApiPostsPostFeedResponses = {
  /**
   * OK
   */
  200: PagedPostPreview;
};

export type MainApiPostsPostFeedResponse = MainApiPostsPostFeedResponses[keyof MainApiPostsPostFeedResponses];

export type MainApiStatusPingData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/ping/';
};

export type MainApiStatusPingResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type MainApiStatusPing2Data = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/ping/';
};

export type MainApiStatusPing2Responses = {
  /**
   * No Content
   */
  204: void;
};

export type MainApiStatusPing2Response = MainApiStatusPing2Responses[keyof MainApiStatusPing2Responses];

export type MainApiStatusWhoamiData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/whoami/';
};

export type MainApiStatusWhoamiResponses = {
  /**
   * OK
   */
  200: WhoAmiISchema;
};

export type MainApiStatusWhoamiResponse = MainApiStatusWhoamiResponses[keyof MainApiStatusWhoamiResponses];

export type MainApiStatusCheckRedirectData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Path
     */
    path: string;
  };
  url: '/api/redirect/';
};

export type MainApiStatusCheckRedirectResponses = {
  /**
   * OK
   */
  200: RedirectSchema;
};

export type MainApiStatusCheckRedirectResponse = MainApiStatusCheckRedirectResponses[keyof MainApiStatusCheckRedirectResponses];

export type MainApiGlobalStateGetGlobalStateData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/state/';
};

export type MainApiGlobalStateGetGlobalStateResponses = {
  /**
   * OK
   */
  200: GlobalState;
};

export type MainApiGlobalStateGetGlobalStateResponse = MainApiGlobalStateGetGlobalStateResponses[keyof MainApiGlobalStateGetGlobalStateResponses];

export type MainApiTagsTagsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/tags/';
};

export type MainApiTagsTagsResponses = {
  /**
   * Response
   *
   * OK
   */
  200: Array<TagDetail>;
};

export type MainApiTagsTagsResponse = MainApiTagsTagsResponses[keyof MainApiTagsTagsResponses];

export type ContactApiSendMailData = {
  body: ContactForm;
  path?: never;
  query?: never;
  url: '/api/contact/';
};

export type ContactApiSendMailErrors = {
  /**
   * Bad Request
   */
  400: unknown;
};

export type ContactApiSendMailResponses = {
  /**
   * No Content
   */
  204: void;
};

export type ContactApiSendMailResponse = ContactApiSendMailResponses[keyof ContactApiSendMailResponses];

export type WebmentionsTesterApiGetTemporaryWebmentionsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Url Path
     */
    url_path: string;
  };
  url: '/api/webmentions_tester/';
};

export type WebmentionsTesterApiGetTemporaryWebmentionsResponses = {
  /**
   * OK
   */
  200: WebmentionTesterSchema;
};

export type WebmentionsTesterApiGetTemporaryWebmentionsResponse = WebmentionsTesterApiGetTemporaryWebmentionsResponses[keyof WebmentionsTesterApiGetTemporaryWebmentionsResponses];

export type WebmentionsTesterApiPostWebmentionData = {
  /**
   * FormParams
   */
  body: {
    /**
     * Url
     */
    url: string;
  };
  path?: never;
  query?: never;
  url: '/api/webmentions_tester/';
};

export type WebmentionsTesterApiPostWebmentionResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GithubApiGetGithubEventsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/github/recent/';
};

export type GithubApiGetGithubEventsResponses = {
  /**
   * OK
   */
  200: GithubRecentEvents;
};

export type GithubApiGetGithubEventsResponse = GithubApiGetGithubEventsResponses[keyof GithubApiGetGithubEventsResponses];
