# Generated by Django 3.1.4 on 2022-01-12 12:02

import datetime
from datetime import timezone

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GithubApiJsonCache",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("retrieved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "valid_until",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2022, 1, 12, 12, 32, 49, 211225, tzinfo=timezone.utc
                        )
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Raw text returned in the original response"
                    ),
                ),
                (
                    "processed_data",
                    models.TextField(
                        blank=True,
                        help_text="Data that was constructed from `content`. Should not be used if the url can be processed in multiple ways!",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GithubRepo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=96, unique=True)),
                ("name", models.CharField(max_length=64)),
                (
                    "languages_json",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
            ],
        ),
    ]
