# Generated by Django 3.2.4 on 2022-01-12 13:34

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("github", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubapijsoncache",
            name="valid_until",
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AlterField(
            model_name="githubrepo",
            name="languages_json",
            field=models.JSONField(default=dict),
        ),
    ]
