# Generated by Django 3.2.4 on 2022-04-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0005_auto_20220411_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubeventupdatecycle',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='githubuserevent',
            options={'ordering': ['-created_at']},
        ),
    ]
