# Generated by Django 4.0.4 on 2022-05-17 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0007_githublanguage_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubetag',
            options={'ordering': ['url']},
        ),
        migrations.AlterModelOptions(
            name='githublanguageusage',
            options={'ordering': ['repository', 'size_bytes']},
        ),
    ]
