# Generated by Django 3.2.4 on 2022-02-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_pageview_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageview',
            options={'ordering': ['-timestamp']},
        ),
    ]
