# Generated by Django 5.2 on 2025-05-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_pageview_modified_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PageView",
        ),
    ]
