name: bma_test

x-common: &common
  env_file: "./.env.dev"
  restart: "no"
  tty: true

x-volume-django: &volume-django
  - type: bind
    source: ./beatonma-django
    target: /django
    read_only: true

services:
  django:
    <<: *common
    build:
      target: test_django
    extends:
      file: ./compose.common.yml
      service: django
    volumes:
      - <<: *volume-django

  next:
    <<: *common
    build:
      target: test_nextjs
    extends:
      file: compose.common.yml
      service: next

  nginx:
    <<: *common
    build:
      target: dev_nginx
    extends:
      file: compose.common.yml
      service: nginx
    depends_on:
      django:
          condition: service_healthy
      next:
          condition: service_healthy
    ports:
      - "82:80"

  cypress:
    <<: *common
    build:
      target: test_cypress
    depends_on:
      nginx:
        condition: service_healthy
    environment:
      - CYPRESS_baseUrl=http://nginx
    volumes:
      - ./cypress:/cypress
