name: bma_dev

volumes:
  postgres:
  generated:

x-common: &common
  env_file: "./.env.dev"
  restart: "unless-stopped"
  tty: true

x-health: &health
  interval: 15s
  timeout: 2s
  start_period: 20s

services:
  db:
    <<: *common
    image: postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432"
    healthcheck:
      test: pg_isready
      <<: *health

  gulp:
    <<: *common
    build:
      dockerfile: ./docker/Dockerfile.dev
      target: gulp_watch
      context: .
    ports:
      - "3000:3000"
      - "3001:3001"
    healthcheck:
      test: curl --header --fail http://localhost:3001 || exit 1
      <<: *health
      start_period: 120s
    volumes:
      - generated:/generated
      - ./beatonma-django:/django:ro
      - ./beatonma-gulp:/app:ro


  django:
    <<: *common
    build:
      dockerfile: ./docker/Dockerfile.dev
      target: django
      context: .
    healthcheck:
      test: curl --header --fail http://localhost:8000/api/ping/ || exit 1
    depends_on:
      db:
        condition: service_healthy
      gulp:
        condition: service_healthy
    ports:
      - "8000"
    volumes:
      - generated:/generated:ro
      - ./beatonma-django:/django:ro
      - /var/www/static:/var/www/static
      - /var/www/media:/var/www/media
