name: bma_test

x-common: &common
  env_file: "./.env.dev"
  restart: "unless-stopped"
  tty: true

x-volume-django: &volume-django
  - type: bind
    source: ./beatonma-django
    target: /django
    read_only: true

services:
  db:
    <<: *common
    extends:
      file: ./compose.common.yml
      service: postgres

  redis:
    <<: *common
    extends:
      file: ./compose.common.yml
      service: redis

  django:
    <<: *common
    build:
      target: test_django
    extends:
      file: ./compose.common.yml
      service: django
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8002:8000"
    volumes:
      - <<: *volume-django

  next:
    <<: *common
    build:
      target: dev_nextjs
    extends:
      file: compose.common.yml
      service: next
    depends_on:
      django:
          condition: service_healthy
    ports:
      - "3002:3000"

  nginx:
    <<: *common
    build:
      target: dev_nginx
    extends:
      file: compose.common.yml
      service: nginx
    depends_on:
      django:
          condition: service_healthy
      next:
          condition: service_healthy
    ports:
      - "82:80"

  celery:
    <<: *common
    build:
      target: dev_celery
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - <<: *volume-django

  cypress:
    <<: *common
    build:
      target: test_cypress
    depends_on:
      nginx:
        condition: service_healthy
    environment:
      - CYPRESS_baseUrl=http://nginx
    volumes:
      - ./cypress:/cypress
