name: bma

volumes:
  letsencrypt:
    # Created via `bma certbot init`.
    name: letsencrypt_keys
    external: true

  letsencrypt_webroot:
    # Created via `bma certbot init`.
    name: letsencrypt_webroot
    external: true

  postgres:
    name: postgres_beatonma


# Common settings for all services
x-common: &common-defaults
  env_file:
    - "./.env.production"
  restart: unless-stopped
  tty: true


x-health: &health
  interval: 60s
  timeout: 10s
  start_period: 40s
  start_interval: 5s
  retries: 3


services:
  db:
    <<: *common-defaults
    image: postgres:15-alpine
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      <<: *health

  django:
    <<: *common-defaults
    build:
      context: .
      target: app
      dockerfile: ./docker/Dockerfile
    image: fallofmath/beatonma:django
    container_name: django
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: curl --head --fail http://localhost:8000/api/ping/ || exit 1
      <<: *health
    volumes:
      - /var/www/static:/var/www/static
      - /var/www/media:/var/www/media
      - /var/www/beatonma:/var/www/beatonma:ro

  next:
    <<: *common-defaults
    build:
      dockerfile: ./docker/Dockerfile
      target: frontend
      context: .
    image: fallofmath/beatonma:next
    container_name: next
    depends_on:
      django:
          condition: service_healthy
    healthcheck:
      test: curl --head --fail http://localhost:3000/health-check/ || exit 1
      <<: *health
    command: npm run start
    environment:
      API_BASE_URL: http://django:8000

  nginx:
    <<: *common-defaults
    build:
      context: .
      target: server
      dockerfile: ./docker/Dockerfile
    image: fallofmath/beatonma:nginx
    container_name: nginx
    depends_on:
      django:
        condition: service_healthy
      next:
        condition: service_healthy
    healthcheck:
      test: curl --head --fail http://localhost/health-check/ || exit 1
      <<: *health
    volumes:
      - /var/log/nginx:/var/log/nginx  # Make logs accessible for fail2ban
      - letsencrypt:/etc/letsencrypt  # letsencrypt certificates
      - letsencrypt_webroot:/var/www/letsencrypt:ro  # letsencrypt renewal webroot
      - /var/www/static:/var/www/static:ro
      - /var/www/media:/var/www/media:ro
    ports:
      - "80:80"
      - "443:443"

  celery:
    <<: *common-defaults
    build:
      context: .
      target: celery
      dockerfile: ./docker/Dockerfile
    image: fallofmath/beatonma:celery
    container_name: celery
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - /var/www/beatonma:/var/www/beatonma:ro

  crontab:
    <<: *common-defaults
    build:
      context: .
      target: crontab
      dockerfile: ./docker/Dockerfile
    image: fallofmath/beatonma:crontab
    container_name: crontab
    depends_on:
      - django
    command: crond -f

  redis:
    <<: *common-defaults
    image: redis:7-alpine
    container_name: redis
    healthcheck:
      test: redis-cli ping
      <<: *health

  server_startup_checks:
    build:
      context: .
      target: server_checks
      dockerfile: ./docker/Dockerfile
    image: fallofmath/beatonma:startup_checks
    links:
      - "nginx:nginx-server-tests"
    container_name: server_startup_checks
    depends_on:
      - nginx
    restart: "on-failure"
