version: "3.9"
name: bma_dev

volumes:
  postgres:
  generated:

x-common: &common
  env_file: ".env"
  restart: "no"
  tty: true

x-health: &health
  interval: 5s
  timeout: 2s
  start_period: 20s

services:
  db:
    <<: *common
    image: postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432"
    healthcheck:
      test: pg_isready
      <<: *health

  gulp:
    build:
      dockerfile: Dockerfile.dev
      target: gulp_watch
    env_file:
      - ".env"
    ports:
      - "3000:3000"
      - "3001:3001"
    healthcheck:
      test: curl --fail http://localhost:3001 || exit 1
      interval: 5s
      start_period: 30s
      timeout: 3s
      retries: 5
    volumes:
      - generated:/generated
      - ./beatonma-django:/django:ro
      - ./beatonma-gulp:/app
    environment:
      - GOOGLE_RECAPTCHA_TOKEN=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
      - TEMPLATE_ROOT=/generated/
      - GIT_HASH=dev

  django:
    <<: *common
    build:
      dockerfile: Dockerfile.dev
      target: app_dev
    depends_on:
      db:
        condition: service_healthy
      gulp:
        condition: service_healthy
    ports:
      - "8000"
    volumes:
      - generated:/generated:ro
      - ./beatonma-django:/django:ro
      - /var/www/static:/var/www/static
      - /var/www/media:/var/www/media
    environment:
      - DEBUG=True
      - TEMPLATE_ROOT=/generated/
      - DJANGO_SUPERUSER_PASSWORD=testpass
      - GIT_HASH=dev
