################################################################################
FROM node:20-alpine AS gulp_watch

RUN apk add \
    git \
    curl

ENV GIT_HASH=dev

WORKDIR /app
COPY ./front/package.json /app
RUN npm install
EXPOSE 3000

ENTRYPOINT ["npm", "run", "watch"]


################################################################################
FROM python:3.11-alpine AS app_dev
ENV PYTHONBUFFERED 1

RUN apk add \
    curl \
    openssh-client \
    git \
    build-base

# Install private libraries from github.
RUN mkdir -p -m 0700 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN --mount=type=ssh pip install git+ssh://git@github.com/beatonma/bmanotify.git
RUN --mount=type=ssh pip install git+ssh://git@github.com/beatonma/bmanotify-django.git

WORKDIR /var/log/beatonma/
WORKDIR /django

ARG REQUIREMENTS_CACHEBUST=0
RUN echo "[requirements]$REQUIREMENTS_CACHEBUST"

COPY ./back/beatonma-django/requirements.txt /django/
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt

ARG CACHEBUST=0
RUN echo "$CACHEBUST"

ENV GIT_HASH="$(shell git rev-parse --short HEAD)"
RUN echo "git hash: '$GIT_HASH'"

COPY ./docker/django/entrypoint.dev.sh /
EXPOSE 8000

ENTRYPOINT ["/entrypoint.dev.sh"]
