################################################################################
FROM node:20-alpine AS gulp_watch

RUN apk add \
    curl

COPY ./docker/gulp/entrypoint.dev.sh /
WORKDIR /app
EXPOSE 3000

ENTRYPOINT /entrypoint.dev.sh


################################################################################
FROM python:3.11-alpine AS django_core
ENV PYTHONBUFFERED 1

RUN apk add \
    curl \
    openssh-client \
    git \
    build-base

# Install private libraries from github.
RUN mkdir -p -m 0700 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN --mount=type=ssh pip install git+ssh://git@github.com/beatonma/bmanotify.git
RUN --mount=type=ssh pip install git+ssh://git@github.com/beatonma/bmanotify-django.git

WORKDIR /var/log/beatonma
WORKDIR /django

COPY ./beatonma-django/requirements.txt /django/
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt


################################################################################
FROM django_core as django

COPY ./docker/django/entrypoint.dev.sh /

EXPOSE 8000
ENTRYPOINT ["/entrypoint.dev.sh"]


################################################################################
FROM django_core as cypress_django

COPY docker/cypress/entrypoint-django.dev.sh /entrypoint.dev.sh

EXPOSE 8000
ENTRYPOINT ["/entrypoint.dev.sh"]


################################################################################
FROM cypress/included as cypress

WORKDIR /cypress
COPY docker/cypress/entrypoint-cypress.dev.sh /entrypoint.dev.sh

EXPOSE 8000
ENTRYPOINT ["/entrypoint.dev.sh"]
