# Generated by Django 5.2 on 2025-05-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bma_dev", "0003_alter_devthemepreview_color_muted_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DevThemePreview",
        ),
    ]
