import random

"""Generated by ChatGPT."""
SAMPLE_TAGS = [
    "MondayMotivation",
    "ThrowbackThursday",
    "TransformationTuesday",
    "WellnessWednesday",
    "FoodieFriday",
    "SaturdayNightLive",
    "SundayFunday",
    "FitnessGoals",
    "TravelLife",
    "DigitalMarketing",
    "ArtInspiration",
    "PhotographyLovers",
    "NatureBeauty",
    "FashionStyle",
    "BookWorm",
    "PetLove",
    "GamingCommunity",
    "MusicLover",
    "EntrepreneurMindset",
    "WomenInTech",
]


def any_tag():
    return random.choice(SAMPLE_TAGS)
