/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/posts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Post Feed */
        get: operations["main_api_posts_post_feed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Post */
        get: operations["main_api_posts_post"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["main_api_search_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/suggestions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Suggestions */
        get: operations["main_api_search_suggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ping/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping */
        get: operations["main_api_status_ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /** Ping */
        head: operations["main_api_status_ping"];
        patch?: never;
        trace?: never;
    };
    "/api/whoami/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whoami */
        get: operations["main_api_status_whoami"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contact/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Mail */
        post: operations["contact_api_send_mail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Input */
        Input: {
            /**
             * Limit
             * @default 24
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /** File */
        File: {
            url: components["schemas"]["Url"];
            thumbnail_url?: components["schemas"]["Url"];
            type: components["schemas"]["MediaType"];
            /** Name */
            name?: string | null;
            /** Description */
            description: string | null;
            fit: components["schemas"]["ImageFit"] | null;
        };
        /**
         * ImageFit
         * @enum {string}
         */
        ImageFit: "cover" | "contain";
        /** Link */
        Link: {
            /** Url */
            url: string;
            /** Description */
            description?: string | null;
            /** Host */
            host?: string | null;
            icon?: components["schemas"]["Url"] | null;
        };
        /**
         * MediaType
         * @enum {string}
         */
        MediaType: "audio" | "video" | "image" | "text" | "unknown";
        /** PagedPostPreview */
        PagedPostPreview: {
            /** Items */
            items: components["schemas"]["PostPreview"][];
            /** Count */
            count: number;
            /** Page Size */
            page_size: number;
            /** Previous */
            previous: number | null;
            /** Next */
            next: number | null;
        };
        /** PostPreview */
        PostPreview: {
            post_type: components["schemas"]["PostType"];
            /** Title */
            title: string | null;
            /** Url */
            url: string;
            /** Is Published */
            is_published: boolean;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            theme?: components["schemas"]["Theme"] | null;
            hero_image: components["schemas"]["File"] | null;
            /** Content Html */
            content_html: string | null;
            /** Content Script */
            content_script: string | null;
            /** Links */
            links: components["schemas"]["Link"][];
            /** Files */
            files: components["schemas"]["File"][];
            /** Tags */
            tags: components["schemas"]["Tag"][];
            /** Is Preview */
            is_preview: boolean;
        };
        /** @enum {string} */
        PostType: "post" | "app" | "changelog";
        /** Tag */
        Tag: {
            /** Name */
            name: string;
        };
        /** Theme */
        Theme: {
            /** Muted */
            muted?: string | null;
            /** Vibrant */
            vibrant?: string | null;
        };
        Url: string;
        /** AppDetail */
        AppDetail: {
            /** @default app */
            post_type: components["schemas"]["PostType"];
            /** Title */
            title: string | null;
            /** Url */
            url: string;
            /** Is Published */
            is_published: boolean;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            theme?: components["schemas"]["Theme"] | null;
            hero_image: components["schemas"]["File"] | null;
            /** Content Html */
            content_html: string | null;
            /** Content Script */
            content_script: string | null;
            /** Links */
            links: components["schemas"]["Link"][];
            /** Files */
            files: components["schemas"]["File"][];
            /** Tags */
            tags: components["schemas"]["Tag"][];
            /** Subtitle */
            subtitle?: string | null;
            /** Hero Html */
            hero_html: string | null;
            /** Mentions */
            mentions: components["schemas"]["Mention"][];
            /** Changelog */
            changelog: components["schemas"]["ChangelogDetail"][];
            /** Icon */
            icon: string | null;
            /** Script */
            script: string | null;
        };
        /** ChangelogDetail */
        ChangelogDetail: {
            /** @default changelog */
            post_type: components["schemas"]["PostType"];
            /** Title */
            title: string | null;
            /** Url */
            url: string;
            /** Is Published */
            is_published: boolean;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            theme?: components["schemas"]["Theme"] | null;
            hero_image: components["schemas"]["File"] | null;
            /** Content Html */
            content_html: string | null;
            /** Content Script */
            content_script: string | null;
            /** Links */
            links: components["schemas"]["Link"][];
            /** Files */
            files: components["schemas"]["File"][];
            /** Tags */
            tags: components["schemas"]["Tag"][];
            /** Subtitle */
            subtitle?: string | null;
            /** Hero Html */
            hero_html: string | null;
            /** Mentions */
            mentions: components["schemas"]["Mention"][];
            /** Version */
            version: string;
        };
        /** HCard */
        HCard: {
            /** Name */
            name: string | null;
            /** Avatar */
            avatar?: string | null;
            /** Homepage */
            homepage: string | null;
        };
        /**
         * IncomingMentionType
         * @description Properties that describe the context of the incoming webmention.
         *
         *     See: https://microformats.org/wiki/h-entry
         * @enum {string}
         */
        IncomingMentionType: "u-bookmark-of" | "u-like-of" | "u-listen-of" | "u-in-reply-to" | "u-repost-of" | "u-translation-of" | "u-watch-of";
        /** Mention */
        Mention: {
            /** Source Url */
            source_url: string;
            hcard: components["schemas"]["HCard"] | null;
            /** Quote */
            quote: string | null;
            type?: components["schemas"]["IncomingMentionType"] | null;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Dev Admin */
            dev_admin: string;
        };
        /** PostDetail */
        PostDetail: {
            /** @default post */
            post_type: components["schemas"]["PostType"];
            /** Title */
            title: string | null;
            /** Url */
            url: string;
            /** Is Published */
            is_published: boolean;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            theme?: components["schemas"]["Theme"] | null;
            hero_image: components["schemas"]["File"] | null;
            /** Content Html */
            content_html: string | null;
            /** Content Script */
            content_script: string | null;
            /** Links */
            links: components["schemas"]["Link"][];
            /** Files */
            files: components["schemas"]["File"][];
            /** Tags */
            tags: components["schemas"]["Tag"][];
            /** Subtitle */
            subtitle?: string | null;
            /** Hero Html */
            hero_html: string | null;
            /** Mentions */
            mentions: components["schemas"]["Mention"][];
        };
        /** SearchResponseSchema */
        SearchResponseSchema: {
            /** Query */
            query: string;
            /** Feed */
            feed: components["schemas"]["SearchResult"][];
        };
        /** SearchResult */
        SearchResult: {
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Timestamp */
            timestamp?: string | null;
            /** Description */
            description?: string | null;
            /** Classname */
            className?: string | null;
        };
        /** WhoAmiISchema */
        WhoAmiISchema: {
            /**
             * Ip
             * Format: ipvanyaddress
             */
            ip: string;
            /** Device */
            device: string;
            /** Os */
            os: string;
            /** Browser */
            browser: string;
        };
        /** ContactForm */
        ContactForm: {
            /** Name */
            name: string;
            /** Contact Info */
            contact_info: string;
            /** Message */
            message: string;
            /** Recaptcha Token */
            recaptcha_token: string;
        };
        /** TempMention */
        TempMention: {
            /** Url */
            url: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            status: components["schemas"]["TempMentionStatus"] | null;
        };
        /** TempMentionStatus */
        TempMentionStatus: {
            /** Successful */
            successful: boolean;
            /** Status Code */
            status_code: number;
            /** Message */
            message: string;
            /** Source Url */
            source_url: string;
            /** Target Url */
            target_url: string;
            /** Endpoint */
            endpoint: string | null;
        };
        /** WebmentionTesterSchema */
        WebmentionTesterSchema: {
            /** Temporary Outgoing Mentions */
            temporary_outgoing_mentions: components["schemas"]["TempMention"][];
            /** Mentions */
            mentions: components["schemas"]["Mention"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    main_api_posts_post_feed: {
        parameters: {
            query?: {
                query?: string;
                tag?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedPostPreview"];
                };
            };
        };
    };
    main_api_posts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostDetail"] | components["schemas"]["AppDetail"] | components["schemas"]["ChangelogDetail"];
                };
            };
        };
    };
    main_api_search_search: {
        parameters: {
            query: {
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponseSchema"];
                };
            };
        };
    };
    main_api_search_suggestions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"][];
                };
            };
        };
    };
    main_api_status_ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    main_api_status_ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    main_api_status_whoami: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoAmiISchema"];
                };
            };
        };
    };
    contact_api_send_mail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactForm"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    webmentions_tester_api_get_temporary_webmentions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebmentionTesterSchema"];
                };
            };
        };
    };
    webmentions_tester_api_post_webmention: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /** Url */
                    url: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
