# Generated by Django 3.2.4 on 2022-04-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0004_auto_20220406_1924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GithubApiJsonCache',
        ),
        migrations.DeleteModel(
            name='GithubRepo',
        ),
    ]
