# Generated by Django 3.2.4 on 2022-04-11 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0006_auto_20220411_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='githublanguage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
