# Generated by Django 5.1.7 on 2025-04-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("github", "0012_rename_githubrepository_api_visible_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GithubIssuesPayload",
            new_name="GithubIssueClosedPayload",
        ),
        migrations.RenameModel(
            old_name="GithubPullRequestPayload",
            new_name="GithubPullRequestMergedPayload",
        ),
        migrations.RenameModel(
            old_name="GithubReleasePayload",
            new_name="GithubReleasePublishedPayload",
        ),
    ]
