# Generated by Django 5.1.7 on 2025-04-14 17:08

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github", "0013_rename_githubissuespayload_githubissueclosedpayload_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cachedresponse",
            name="data",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
