# Generated by Django 6.0.1 on 2026-01-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0014_alter_cachedresponse_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubetag',
            name='etag',
            field=models.CharField(editable=False, max_length=256),
        ),
    ]
