# Generated by Django 4.1.5 on 2023-04-08 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("wurdle", "0003_validwurd_modified_at_wurd_modified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validwurd",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
