from github.tasks.api_models import Event

_SAMPLE_USER = {
    "login": "beatonma",
    "id": 12682046,
    "node_id": "MDQ6VXNlcjEyNjgyMDQ2",
    "avatar_url": "https://avatars.githubusercontent.com/u/12682046?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/beatonma",
    "html_url": "https://github.com/beatonma",
    "followers_url": "https://api.github.com/users/beatonma/followers",
    "following_url": "https://api.github.com/users/beatonma/following{/other_user}",
    "gists_url": "https://api.github.com/users/beatonma/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/beatonma/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/beatonma/subscriptions",
    "organizations_url": "https://api.github.com/users/beatonma/orgs",
    "repos_url": "https://api.github.com/users/beatonma/repos",
    "events_url": "https://api.github.com/users/beatonma/events{/privacy}",
    "received_events_url": "https://api.github.com/users/beatonma/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": False,
}
_SAMPLE_USER_MINI = {
    "id": 12682046,
    "login": "beatonma",
    "display_login": "beatonma",
    "gravatar_id": "",
    "url": "https://api.github.com/users/beatonma",
    "avatar_url": "https://avatars.githubusercontent.com/u/12682046?",
}

_SAMPLE_REPO_MINI = {
    "id": 179150364,
    "name": "beatonma/django-wm",
    "url": "https://api.github.com/repos/beatonma/django-wm",
}
_SAMPLE_REPO_FULL = {
    "id": 179150364,
    "node_id": "MDEwOlJlcG9zaXRvcnkxODg1OTUxOTU=",
    "name": "django-wm",
    "full_name": "beatonma/django-wm",
    "private": False,
    "owner": _SAMPLE_USER,
    "html_url": "https://github.com/beatonma/django-wm",
    "description": "Automatic Webmention functionality for Django models",
    "fork": False,
    "url": "https://api.github.com/repos/beatonma/django-wm",
    "forks_url": "https://api.github.com/repos/beatonma/django-wm/forks",
    "keys_url": "https://api.github.com/repos/beatonma/django-wm/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/beatonma/django-wm/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/beatonma/django-wm/teams",
    "hooks_url": "https://api.github.com/repos/beatonma/django-wm/hooks",
    "issue_events_url": "https://api.github.com/repos/beatonma/django-wm/issues/events{/number}",
    "events_url": "https://api.github.com/repos/beatonma/django-wm/events",
    "assignees_url": "https://api.github.com/repos/beatonma/django-wm/assignees{/user}",
    "branches_url": "https://api.github.com/repos/beatonma/django-wm/branches{/branch}",
    "tags_url": "https://api.github.com/repos/beatonma/django-wm/tags",
    "blobs_url": "https://api.github.com/repos/beatonma/django-wm/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/beatonma/django-wm/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/beatonma/django-wm/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/beatonma/django-wm/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/beatonma/django-wm/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/beatonma/django-wm/languages",
    "stargazers_url": "https://api.github.com/repos/beatonma/django-wm/stargazers",
    "contributors_url": "https://api.github.com/repos/beatonma/django-wm/contributors",
    "subscribers_url": "https://api.github.com/repos/beatonma/django-wm/subscribers",
    "subscription_url": "https://api.github.com/repos/beatonma/django-wm/subscription",
    "commits_url": "https://api.github.com/repos/beatonma/django-wm/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/beatonma/django-wm/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/beatonma/django-wm/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/beatonma/django-wm/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/beatonma/django-wm/contents/{+path}",
    "compare_url": "https://api.github.com/repos/beatonma/django-wm/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/beatonma/django-wm/merges",
    "archive_url": "https://api.github.com/repos/beatonma/django-wm/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/beatonma/django-wm/downloads",
    "issues_url": "https://api.github.com/repos/beatonma/django-wm/issues{/number}",
    "pulls_url": "https://api.github.com/repos/beatonma/django-wm/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/beatonma/django-wm/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/beatonma/django-wm/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/beatonma/django-wm/labels{/name}",
    "releases_url": "https://api.github.com/repos/beatonma/django-wm/releases{/id}",
    "deployments_url": "https://api.github.com/repos/beatonma/django-wm/deployments",
    "created_at": "2019-05-25T17:35:58Z",
    "updated_at": "2025-08-04T15:07:56Z",
    "pushed_at": "2025-08-30T13:20:53Z",
    "git_url": "git://github.com/beatonma/django-wm.git",
    "ssh_url": "git@github.com:beatonma/django-wm.git",
    "clone_url": "https://github.com/beatonma/django-wm.git",
    "svn_url": "https://github.com/beatonma/django-wm",
    "homepage": "",
    "size": 4631,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Python",
    "has_issues": True,
    "has_projects": True,
    "has_downloads": True,
    "has_wiki": True,
    "has_pages": False,
    "has_discussions": False,
    "forks_count": 0,
    "mirror_url": None,
    "archived": False,
    "disabled": False,
    "open_issues_count": 1,
    "license": None,
    "allow_forking": True,
    "is_template": False,
    "web_commit_signoff_required": False,
    "topics": [],
    "visibility": "public",
    "forks": 0,
    "open_issues": 1,
    "watchers": 0,
    "default_branch": "main",
}

SAMPLE_CREATE_EVENT = Event.model_validate(
    {
        "id": "20975491109",
        "type": "CreateEvent",
        "actor": _SAMPLE_USER_MINI,
        "repo": _SAMPLE_REPO_MINI,
        "payload": {
            "ref": "2.3.0",
            "ref_type": "branch",
            "master_branch": "master",
            "description": "Automatic Webmention functionality for Django models",
            "pusher_type": "user",
        },
        "public": True,
        "created_at": "2022-03-28T14:53:54Z",
    }
)

SAMPLE_PULLREQUEST_EVENT = Event.model_validate(
    {
        "id": "2685446690",
        "type": "PullRequestEvent",
        "actor": _SAMPLE_USER_MINI,
        "repo": _SAMPLE_REPO_MINI,
        "payload": {
            "action": "closed",
            "number": 8,
            "pull_request": {"unused data removed for tests": None},
            "label": None,
            "labels": [],
        },
        "public": True,
        "created_at": "2025-07-22T12:46:36Z",
    }
)

SAMPLE_PULLREQUEST_JSON = {
    "url": "https://api.github.com/repos/beatonma/django-wm/pulls/8",
    "id": 2685446690,
    "node_id": "PR_kwDOCz27-86gEKoi",
    "html_url": "https://github.com/beatonma/django-wm/pull/8",
    "diff_url": "https://github.com/beatonma/django-wm/pull/8.diff",
    "patch_url": "https://github.com/beatonma/django-wm/pull/8.patch",
    "issue_url": "https://api.github.com/repos/beatonma/django-wm/issues/8",
    "number": 8,
    "state": "closed",
    "locked": False,
    "title": "Bump form-data from 4.0.3 to 4.0.4 in /frontend",
    "user": {
        "login": "dependabot[bot]",
        "id": 49699333,
        "node_id": "MDM6Qm90NDk2OTkzMzM=",
        "avatar_url": "https://avatars.githubusercontent.com/in/29110?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/dependabot%5Bbot%5D",
        "html_url": "https://github.com/apps/dependabot",
        "followers_url": "https://api.github.com/users/dependabot%5Bbot%5D/followers",
        "following_url": "https://api.github.com/users/dependabot%5Bbot%5D/following{/other_user}",
        "gists_url": "https://api.github.com/users/dependabot%5Bbot%5D/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/dependabot%5Bbot%5D/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dependabot%5Bbot%5D/subscriptions",
        "organizations_url": "https://api.github.com/users/dependabot%5Bbot%5D/orgs",
        "repos_url": "https://api.github.com/users/dependabot%5Bbot%5D/repos",
        "events_url": "https://api.github.com/users/dependabot%5Bbot%5D/events{/privacy}",
        "received_events_url": "https://api.github.com/users/dependabot%5Bbot%5D/received_events",
        "type": "Bot",
        "user_view_type": "public",
        "site_admin": False,
    },
    "body": "\n\n[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=form-data&package-manager=npm_and_yarn&previous-version=4.0.3&new-version=4.0.4)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)\n\nDependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.\n\n[//]: # (dependabot-automerge-start)\n[//]: # (dependabot-automerge-end)\n\n---\n\n<details>\n<summary>Dependabot commands and options</summary>\n<br />\n\nYou can trigger Dependabot actions by commenting on this PR:\n- `@dependabot rebase` will rebase this PR\n- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it\n- `@dependabot merge` will merge this PR after your CI passes on it\n- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it\n- `@dependabot cancel merge` will cancel a previously requested merge and block automerging\n- `@dependabot reopen` will reopen this PR if it is closed\n- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually\n- `@dependabot show <dependency name> ignore conditions` will show all of the ignore conditions of the specified dependency\n- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)\n- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)\n- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)\nYou can disable automated security fix PRs for this repo from the [Security Alerts page](https://github.com/beatonma/django-wm/network/alerts).\n\n</details>",
    "created_at": "2025-07-22T12:46:36Z",
    "updated_at": "2025-08-02T17:12:14Z",
    "closed_at": "2025-08-02T17:12:07Z",
    "merged_at": "2025-08-02T17:12:07Z",
    "merge_commit_sha": "4a14fdc9042d57c58a42b1d3ac100bfdd0f5d986",
    "assignee": None,
    "assignees": [],
    "requested_reviewers": [],
    "requested_teams": [],
    "labels": [
        {
            "id": 1768159525,
            "node_id": "MDU6TGFiZWwxNzY4MTU5NTI1",
            "url": "https://api.github.com/repos/beatonma/django-wm/labels/dependencies",
            "name": "dependencies",
            "color": "0366d6",
            "default": False,
            "description": "Pull requests that update a dependency file",
        },
        {
            "id": 8984830789,
            "node_id": "LA_kwDOCz27-88AAAACF4mjRQ",
            "url": "https://api.github.com/repos/beatonma/django-wm/labels/javascript",
            "name": "javascript",
            "color": "168700",
            "default": False,
            "description": "Pull requests that update javascript code",
        },
    ],
    "milestone": None,
    "draft": False,
    "commits_url": "https://api.github.com/repos/beatonma/django-wm/pulls/8/commits",
    "review_comments_url": "https://api.github.com/repos/beatonma/django-wm/pulls/8/comments",
    "review_comment_url": "https://api.github.com/repos/beatonma/django-wm/pulls/comments{/number}",
    "comments_url": "https://api.github.com/repos/beatonma/django-wm/issues/8/comments",
    "statuses_url": "https://api.github.com/repos/beatonma/django-wm/statuses/ea8632687030e2df416b7a7c80c356589cfd32f3",
    "head": {
        "label": "beatonma:dependabot/npm_and_yarn/frontend/form-data-4.0.4",
        "ref": "dependabot/npm_and_yarn/frontend/form-data-4.0.4",
        "sha": "ea8632687030e2df416b7a7c80c356589cfd32f3",
        "user": _SAMPLE_USER,
        "repo": _SAMPLE_REPO_FULL,
    },
    "base": {
        "label": "beatonma:main",
        "ref": "main",
        "sha": "a2d4f747d0c1ef33d7007908080ca701b7078f2a",
        "user": _SAMPLE_USER,
        "repo": _SAMPLE_REPO_FULL,
    },
    "_links": {
        "self": {"href": "https://api.github.com/repos/beatonma/django-wm/pulls/8"},
        "html": {"href": "https://github.com/beatonma/django-wm/pull/8"},
        "issue": {"href": "https://api.github.com/repos/beatonma/django-wm/issues/8"},
        "comments": {
            "href": "https://api.github.com/repos/beatonma/django-wm/issues/8/comments"
        },
        "review_comments": {
            "href": "https://api.github.com/repos/beatonma/django-wm/pulls/8/comments"
        },
        "review_comment": {
            "href": "https://api.github.com/repos/beatonma/django-wm/pulls/comments{/number}"
        },
        "commits": {
            "href": "https://api.github.com/repos/beatonma/django-wm/pulls/8/commits"
        },
        "statuses": {
            "href": "https://api.github.com/repos/beatonma/django-wm/statuses/ea8632687030e2df416b7a7c80c356589cfd32f3"
        },
    },
    "author_association": "CONTRIBUTOR",
    "auto_merge": None,
    "active_lock_reason": None,
    "merged": True,
    "mergeable": None,
    "rebaseable": None,
    "mergeable_state": "unknown",
    "merged_by": _SAMPLE_USER,
    "comments": 0,
    "review_comments": 0,
    "maintainer_can_modify": False,
    "commits": 1,
    "additions": 3,
    "deletions": 3,
    "changed_files": 1,
}


SAMPLE_RELEASE_EVENT = Event.model_validate(
    {
        "id": "20950698922",
        "type": "ReleaseEvent",
        "actor": _SAMPLE_USER_MINI,
        "repo": {
            "id": 179150364,
            "name": "octocat/Hello-World",
            "url": "https://api.github.com/repos/octocat/Hello-World",
        },
        "payload": {
            "action": "published",
            "changes": {},
            "release": {
                "url": "https://api.github.com/repos/octocat/Hello-World/releases/1",
                "html_url": "https://github.com/octocat/Hello-World/releases/v1.0.0",
                "assets_url": "https://api.github.com/repos/octocat/Hello-World/releases/1/assets",
                "upload_url": "https://uploads.github.com/repos/octocat/Hello-World/releases/1/assets{?name,label}",
                "tarball_url": "https://api.github.com/repos/octocat/Hello-World/tarball/v1.0.0",
                "zipball_url": "https://api.github.com/repos/octocat/Hello-World/zipball/v1.0.0",
                "discussion_url": "https://github.com/octocat/Hello-World/discussions/90",
                "id": 1,
                "node_id": "MDc6UmVsZWFzZTE=",
                "tag_name": "v1.0.0",
                "target_commitish": "master",
                "name": "v1.0.0",
                "body": "Description of the release",
                "draft": False,
                "prerelease": False,
                "created_at": "2013-02-27T19:35:32Z",
                "published_at": "2013-02-27T19:35:32Z",
                "author": {},
                "assets": [],
            },
        },
        "public": True,
        "created_at": "2022-03-26T14:03:05Z",
    }
)

SAMPLE_ISSUES_EVENT = Event.model_validate(
    {
        "id": "20950698727",
        "type": "IssuesEvent",
        "actor": _SAMPLE_USER_MINI,
        "repo": _SAMPLE_REPO_MINI,
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/beatonma/django-wm/issues/26",
                "repository_url": "https://api.github.com/repos/beatonma/django-wm",
                "labels_url": "https://api.github.com/repos/beatonma/django-wm/issues/26/labels{/name}",
                "comments_url": "https://api.github.com/repos/beatonma/django-wm/issues/26/comments",
                "events_url": "https://api.github.com/repos/beatonma/django-wm/issues/26/events",
                "html_url": "https://github.com/beatonma/django-wm/issues/26",
                "id": 1181100859,
                "node_id": "I_kwDOCq2eHM5GZis7",
                "number": 26,
                "title": "Expand the allowed versions of the required requests package?",
                "user": {},
                "labels": [],
                "state": "closed",
                "locked": False,
                "assignee": None,
                "assignees": [],
                "milestone": None,
                "comments": 0,
                "created_at": "2022-03-25T18:22:12Z",
                "updated_at": "2022-03-26T14:03:03Z",
                "closed_at": "2022-03-26T14:03:03Z",
                "author_association": "NONE",
                "active_lock_reason": None,
                "body": "Issue description and suchlike",
                "reactions": {},
                "timeline_url": "https://api.github.com/repos/beatonma/django-wm/issues/26/timeline",
                "performed_via_github_app": None,
            },
        },
        "public": True,
        "created_at": "2022-03-26T14:03:04Z",
    }
)

SAMPLE_WIKI_EVENT = Event.model_validate(
    {
        "id": "21143487061",
        "type": "GollumEvent",
        "actor": _SAMPLE_USER_MINI,
        "repo": _SAMPLE_REPO_MINI,
        "payload": {
            "pages": [
                {
                    "page_name": "Home",
                    "title": "Home",
                    "summary": None,
                    "action": "created",
                    "sha": "0c991f93a25747a8ca9bacabbd913750f2aa4cbf",
                    "html_url": "https://github.com/beatonma/snommoc/wiki/Home",
                }
            ]
        },
        "public": True,
        "created_at": "2022-04-06T13:28:39Z",
    }
)


"""
As of October 2025, commit data is no longer included in the PushEvent payload
and must be retrieved with further API calls for each repository.
Sample url: https://api.github.com/repos/<USERNAME>/<REPOSITORY>/commits
"""
SAMPLE_PUSH_EVENT = Event.model_validate(
    {
        "id": "5123301820",
        "type": "PushEvent",
        "actor": _SAMPLE_USER_MINI,
        "repo": _SAMPLE_REPO_MINI,
        "payload": {
            "repository_id": 179150364,
            "push_id": 27411889285,
            "ref": "refs/heads/main",
            "head": "382de5ba4dca3aea9f3da4053ec499b15b5d8a45",
            "before": "12a490e6961ae1e8e3be402c3417dbe82531c115",
        },
        "public": False,
        "created_at": "2025-10-10T16:49:28Z",
    }
)

SAMPLE_PUSH_COMMITS_JSON = [
    {
        "sha": "382de5ba4dca3aea9f3da4053ec499b15b5d8a45",
        "node_id": "C_kwDOP0EPy9oAKDM4MmRlNWJhNGRjYTNhZWE5ZjNkYTQwNTNlYzQ5OWIxNWI1ZDhhNDU",
        "commit": {
            "author": {
                "name": "Michael Beaton",
                "email": "beatonma@gmail.com",
                "date": "2025-10-10T15:38:18Z",
            },
            "committer": {
                "name": "Michael Beaton",
                "email": "beatonma@gmail.com",
                "date": "2025-10-10T16:49:07Z",
            },
            "message": "newest commit",
            "tree": {
                "sha": "4dcf22617e2058a29c87d62adc52a4a3e5424c50",
                "url": "https://api.github.com/repos/beatonma/django-wm/git/trees/4dcf22617e2058a29c87d62adc52a4a3e5424c50",
            },
            "url": "https://api.github.com/repos/beatonma/django-wm/git/commits/382de5ba4dca3aea9f3da4053ec499b15b5d8a45",
            "comment_count": 0,
            "verification": {"unused data removed for tests": None},
        },
        "url": "https://api.github.com/repos/beatonma/django-wm/commits/382de5ba4dca3aea9f3da4053ec499b15b5d8a45",
        "html_url": "https://github.com/beatonma/django-wm/commit/382de5ba4dca3aea9f3da4053ec499b15b5d8a45",
        "comments_url": "https://api.github.com/repos/beatonma/django-wm/commits/382de5ba4dca3aea9f3da4053ec499b15b5d8a45/comments",
        "author": _SAMPLE_USER,
        "committer": {"unused data removed for tests": None},
        "parents": [],
    },
    {
        "sha": "c50f16fc5fdca6728efb18cdf53fa7dbfb8ab0b7",
        "node_id": "C_kwDOP0EPy9oAKGM1MGYxNmZjNWZkY2E2NzI4ZWZiMThjZGY1M2ZhN2RiZmI4YWIwYjc",
        "commit": {
            "author": {
                "name": "Michael Beaton",
                "email": "beatonma@gmail.com",
                "date": "2025-10-10T15:19:15Z",
            },
            "committer": {
                "name": "Michael Beaton",
                "email": "beatonma@gmail.com",
                "date": "2025-10-10T16:49:07Z",
            },
            "message": "",
            "tree": {
                "sha": "6a51bf1486bdb52faabd8d15638f9e62906c433b",
                "url": "https://api.github.com/repos/beatonma/django-wm/git/trees/6a51bf1486bdb52faabd8d15638f9e62906c433b",
            },
            "url": "https://api.github.com/repos/beatonma/django-wm/git/commits/c50f16fc5fdca6728efb18cdf53fa7dbfb8ab0b7",
            "comment_count": 0,
            "verification": {"unused data removed for tests": None},
        },
        "url": "https://api.github.com/repos/beatonma/django-wm/commits/c50f16fc5fdca6728efb18cdf53fa7dbfb8ab0b7",
        "html_url": "https://github.com/beatonma/django-wm/commit/c50f16fc5fdca6728efb18cdf53fa7dbfb8ab0b7",
        "comments_url": "https://api.github.com/repos/beatonma/django-wm/commits/c50f16fc5fdca6728efb18cdf53fa7dbfb8ab0b7/comments",
        "author": _SAMPLE_USER,
        "committer": {"unused data removed for tests": None},
        "parents": [],
    },
    {
        "sha": "bb5db9bc7da36965a07d51b65772980188b90dbe",
        "node_id": "C_kwDOP0EPy9oAKGJiNWRiOWJjN2RhMzY5NjVhMDdkNTFiNjU3NzI5ODAxODhiOTBkYmU",
        "commit": {
            "author": {
                "name": "Michael Beaton",
                "email": "beatonma@gmail.com",
                "date": "2025-10-10T15:12:15Z",
            },
            "committer": {
                "name": "Michael Beaton",
                "email": "beatonma@gmail.com",
                "date": "2025-10-10T15:12:15Z",
            },
            "message": "",
            "tree": {
                "sha": "053d6502c2bce8048ad7b54bf0d8675f7e3d6a79",
                "url": "https://api.github.com/repos/beatonma/django-wm/git/trees/053d6502c2bce8048ad7b54bf0d8675f7e3d6a79",
            },
            "url": "https://api.github.com/repos/beatonma/django-wm/git/commits/bb5db9bc7da36965a07d51b65772980188b90dbe",
            "comment_count": 0,
            "verification": {"unused data removed for tests": None},
        },
        "url": "https://api.github.com/repos/beatonma/django-wm/commits/bb5db9bc7da36965a07d51b65772980188b90dbe",
        "html_url": "https://github.com/beatonma/django-wm/commit/bb5db9bc7da36965a07d51b65772980188b90dbe",
        "comments_url": "https://api.github.com/repos/beatonma/django-wm/commits/bb5db9bc7da36965a07d51b65772980188b90dbe/comments",
        "author": _SAMPLE_USER,
        "committer": {"unused data removed for tests": None},
        "parents": [],
    },
    {
        "sha": "df42101bfd0aa4c963304dc96cf6152ce841e804",
        "node_id": "C_kwDOP0EPy9oAKGRmNDIxMDFiZmQwYWE0Yzk2MzMwNGRjOTZjZjYxNTJjZTg0MWU4MDQ",
        "commit": {
            "author": {
                "name": "Michael Beaton",
                "email": "beatonma@gmail.com",
                "date": "2025-10-08T12:31:21Z",
            },
            "committer": {
                "name": "Michael Beaton",
                "email": "beatonma@gmail.com",
                "date": "2025-10-08T12:31:21Z",
            },
            "message": "",
            "tree": {
                "sha": "b04233dfa8e815e09000964b7af4e48710c0d938",
                "url": "https://api.github.com/repos/beatonma/django-wm/git/trees/b04233dfa8e815e09000964b7af4e48710c0d938",
            },
            "url": "https://api.github.com/repos/beatonma/django-wm/git/commits/df42101bfd0aa4c963304dc96cf6152ce841e804",
            "comment_count": 0,
            "verification": {"unused data removed for tests": None},
        },
        "url": "https://api.github.com/repos/beatonma/django-wm/commits/df42101bfd0aa4c963304dc96cf6152ce841e804",
        "html_url": "https://github.com/beatonma/django-wm/commit/df42101bfd0aa4c963304dc96cf6152ce841e804",
        "comments_url": "https://api.github.com/repos/beatonma/django-wm/commits/df42101bfd0aa4c963304dc96cf6152ce841e804/comments",
        "author": _SAMPLE_USER,
        "committer": {"unused data removed for tests": None},
        "parents": [],
    },
    {
        "sha": "32f3c19834243f505832d2809cf1249594227132",
        "node_id": "C_kwDOP0EPy9oAKDMyZjNjMTk4MzQyNDNmNTA1ODMyZDI4MDljZjEyNDk1OTQyMjcxMzI",
        "commit": {
            "author": {
                "name": "Michael Beaton",
                "email": "beatonma@gmail.com",
                "date": "2025-10-06T09:54:10Z",
            },
            "committer": {
                "name": "Michael Beaton",
                "email": "beatonma@gmail.com",
                "date": "2025-10-06T09:54:10Z",
            },
            "message": "",
            "tree": {
                "sha": "a52a8eb2f41aefe13a57c8ff38de995ba26e6494",
                "url": "https://api.github.com/repos/beatonma/django-wm/git/trees/a52a8eb2f41aefe13a57c8ff38de995ba26e6494",
            },
            "url": "https://api.github.com/repos/beatonma/django-wm/git/commits/32f3c19834243f505832d2809cf1249594227132",
            "comment_count": 0,
            "verification": {"unused data removed for tests": None},
        },
        "url": "https://api.github.com/repos/beatonma/django-wm/commits/32f3c19834243f505832d2809cf1249594227132",
        "html_url": "https://github.com/beatonma/django-wm/commit/32f3c19834243f505832d2809cf1249594227132",
        "comments_url": "https://api.github.com/repos/beatonma/django-wm/commits/32f3c19834243f505832d2809cf1249594227132/comments",
        "author": _SAMPLE_USER,
        "committer": {"unused data removed for tests": None},
        "parents": [],
    },
    {
        "sha": "4c607acc7c8943245c458377321591cff5d702e6",
        "node_id": "C_kwDOP0EPy9oAKDRjNjA3YWNjN2M4OTQzMjQ1YzQ1ODM3NzMyMTU5MWNmZjVkNzAyZTY",
        "commit": {
            "author": {
                "name": "Michael Beaton",
                "email": "beatonma@gmail.com",
                "date": "2025-10-04T12:38:49Z",
            },
            "committer": {
                "name": "Michael Beaton",
                "email": "beatonma@gmail.com",
                "date": "2025-10-04T12:38:49Z",
            },
            "message": "",
            "tree": {
                "sha": "c46bafed723bfbdab5249c1cb4d7165e70d97193",
                "url": "https://api.github.com/repos/beatonma/django-wm/git/trees/c46bafed723bfbdab5249c1cb4d7165e70d97193",
            },
            "url": "https://api.github.com/repos/beatonma/django-wm/git/commits/4c607acc7c8943245c458377321591cff5d702e6",
            "comment_count": 0,
            "verification": {"unused data removed for tests": None},
        },
        "url": "https://api.github.com/repos/beatonma/django-wm/commits/4c607acc7c8943245c458377321591cff5d702e6",
        "html_url": "https://github.com/beatonma/django-wm/commit/4c607acc7c8943245c458377321591cff5d702e6",
        "comments_url": "https://api.github.com/repos/beatonma/django-wm/commits/4c607acc7c8943245c458377321591cff5d702e6/comments",
        "author": _SAMPLE_USER,
        "committer": {"unused data removed for tests": None},
        "parents": [],
    },
    {
        "sha": "30606892ad7918e079ec220215414eade38043c9",
        "node_id": "C_kwDOP0EPy9oAKDMwNjA2ODkyYWQ3OTE4ZTA3OWVjMjIwMjE1NDE0ZWFkZTM4MDQzYzk",
        "commit": {
            "author": {
                "name": "Michael Beaton",
                "email": "beatonma@gmail.com",
                "date": "2025-10-03T18:30:31Z",
            },
            "committer": {
                "name": "Michael Beaton",
                "email": "beatonma@gmail.com",
                "date": "2025-10-03T18:30:31Z",
            },
            "message": "oldest commit",
            "tree": {
                "sha": "f877abd243da018996bc384b525fd06dba46356a",
                "url": "https://api.github.com/repos/beatonma/django-wm/git/trees/f877abd243da018996bc384b525fd06dba46356a",
            },
            "url": "https://api.github.com/repos/beatonma/django-wm/git/commits/30606892ad7918e079ec220215414eade38043c9",
            "comment_count": 0,
            "verification": {"unused data removed for tests": None},
        },
        "url": "https://api.github.com/repos/beatonma/django-wm/commits/30606892ad7918e079ec220215414eade38043c9",
        "html_url": "https://github.com/beatonma/django-wm/commit/30606892ad7918e079ec220215414eade38043c9",
        "comments_url": "https://api.github.com/repos/beatonma/django-wm/commits/30606892ad7918e079ec220215414eade38043c9/comments",
        "author": _SAMPLE_USER,
        "committer": {"unused data removed for tests": None},
        "parents": [],
    },
    {
        "sha": "12a490e6961ae1e8e3be402c3417dbe82531c115",
        "node_id": "C_kwDOP0EPy9oAKDEyYTQ5MGU2OTYxYWUxZThlM2JlNDAyYzM0MTdkYmU4MjUzMWMxMTU",
        "commit": {
            "author": {
                "name": "Michael Beaton",
                "email": "beatonma@gmail.com",
                "date": "2025-10-03T17:55:27Z",
            },
            "committer": {
                "name": "Michael Beaton",
                "email": "beatonma@gmail.com",
                "date": "2025-10-03T17:55:27Z",
            },
            "message": "commit from previous event",
            "tree": {
                "sha": "ea3d4f851155284e56a3c55a0320d22274344590",
                "url": "https://api.github.com/repos/beatonma/django-wm/git/trees/ea3d4f851155284e56a3c55a0320d22274344590",
            },
            "url": "https://api.github.com/repos/beatonma/django-wm/git/commits/12a490e6961ae1e8e3be402c3417dbe82531c115",
            "comment_count": 0,
            "verification": {"unused data removed for tests": None},
        },
        "url": "https://api.github.com/repos/beatonma/django-wm/commits/12a490e6961ae1e8e3be402c3417dbe82531c115",
        "html_url": "https://github.com/beatonma/django-wm/commit/12a490e6961ae1e8e3be402c3417dbe82531c115",
        "comments_url": "https://api.github.com/repos/beatonma/django-wm/commits/12a490e6961ae1e8e3be402c3417dbe82531c115/comments",
        "author": _SAMPLE_USER,
        "committer": {"unused data removed for tests": None},
        "parents": [],
    },
]
