# Generated by Django 4.1.5 on 2023-04-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bma_dev', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devthemepreview',
            name='color_on_muted',
        ),
        migrations.RemoveField(
            model_name='devthemepreview',
            name='color_on_vibrant',
        ),
    ]
