ARG NODE_VERSION=22
ARG PYTHON_VERSION=3.12

################################################################################
FROM node:${NODE_VERSION}-alpine AS frontend

RUN apk add curl
RUN adduser -u 1001 -s /bin/sh -D app
USER app

WORKDIR /app
COPY --chown=app:app ./frontend/package.json ./frontend/package-lock.json /app/
RUN npm install

COPY --chown=app:app ./frontend /app


################################################################################
FROM python:${PYTHON_VERSION}-alpine AS django_core
ENV PYTHONBUFFERED 1

RUN apk add \
    curl \
    openssh-client \
    git \
    build-base \
    libwebp

# Install private libraries from github.
RUN mkdir -p -m 0700 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN --mount=type=ssh pip install git+ssh://git@github.com/beatonma/bmanotify.git
RUN --mount=type=ssh pip install git+ssh://git@github.com/beatonma/bmanotify-django.git --force-reinstall

WORKDIR /var/log/beatonma
WORKDIR /django

COPY ./beatonma-django/requirements.txt /django/
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt


################################################################################
FROM django_core AS django

COPY ./docker/django/entrypoint.dev.sh /

EXPOSE 8000
ENTRYPOINT ["/entrypoint.dev.sh"]


################################################################################
FROM django_core AS celery

ENTRYPOINT ["celery", "-A", "beatonma", "worker", "-l", "info"]


################################################################################
FROM nginx:latest AS nginx

COPY ./docker/nginx/nginx.dev.conf /etc/nginx/nginx.conf

EXPOSE 80
