ARG NODE_VERSION=21
ARG PYTHON_VERSION=3.12

################################################################################
FROM node:${NODE_VERSION}-alpine AS gulp_watch

RUN apk add \
    curl

WORKDIR /app
EXPOSE 3000

ARG task="watch"
RUN echo "task=$task"
RUN { echo "npm install"; echo "npm run gulp -- $task"; } > /tmp/entrypoint.dev.sh
RUN chmod 764 /tmp/entrypoint.dev.sh

ENTRYPOINT /tmp/entrypoint.dev.sh
CMD ["$task"]


################################################################################
FROM python:${PYTHON_VERSION}-alpine AS django_core
ENV PYTHONBUFFERED 1

RUN apk add \
    curl \
    openssh-client \
    git \
    build-base

# Install private libraries from github.
RUN mkdir -p -m 0700 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN --mount=type=ssh pip install git+ssh://git@github.com/beatonma/bmanotify.git
RUN --mount=type=ssh pip install git+ssh://git@github.com/beatonma/bmanotify-django.git

WORKDIR /var/log/beatonma
WORKDIR /django

COPY ./beatonma-django/requirements.txt /django/
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt


################################################################################
FROM django_core as django

COPY ./docker/django/entrypoint.dev.sh /

EXPOSE 8000
ENTRYPOINT ["/entrypoint.dev.sh"]
