# Generated by Django 3.2.4 on 2022-02-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_pageview_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='ua_browser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='ua_device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='ua_os',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
