# Generated by Django 3.2.4 on 2022-03-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20220210_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
