# Generated by Django 3.2.4 on 2022-04-11 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_pageview_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageview',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='pageview',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='pageview',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
