import random
from dataclasses import dataclass


@dataclass
class SamplePost:
    title: str | None = None
    summary: str | None = None
    content: str | None = None


"""Generated by ChatGPT.

It only gave me 4 results so I asked for them 4 at a time.
It then started to repeat itself so I asked for examples with space or STEM themes
which turned out much more interesting... Not that that matters - it's just sample data.
"""
SAMPLE_POSTS = list(
    map(
        lambda item: SamplePost(**item),
        [
            {
                "title": "Introduction to Python Programming",
                "summary": "Learn the basics of Python programming language.",
                "content": "Python is a popular high-level programming language for web development, scientific computing, data analysis, artificial intelligence, and more. It is easy to learn and use, with a simple syntax that emphasizes readability and reduces the cost of program maintenance. Python supports multiple programming paradigms, including procedural, functional, and object-oriented programming. Here are some of the key features of Python:\n\n- Interpreted language\n- Dynamically typed\n- Automatic memory management\n- Rich standard library\n- Cross-platform\n- Open-source",
            },
            {
                "title": "The Benefits of Meditation",
                "summary": "Discover the advantages of a daily meditation practice.",
                "content": "Meditation is a powerful tool for reducing stress, increasing focus and clarity, and improving overall well-being. Regular meditation practice has been linked to a range of health benefits, including:\n\n- Lowered blood pressure\n- Reduced anxiety and depression\n- Improved sleep quality\n- Enhanced immune function\n- Increased empathy and compassion\n- Improved cognitive function\n\nTo get started with meditation, find a quiet and comfortable space, set aside a few minutes each day, and focus on your breath or a simple mantra. Over time, you may find that meditation becomes an integral part of your daily routine.",
            },
            {
                "title": "The Basics of HTML",
                "summary": "Learn the fundamentals of HTML for web development.",
                "content": "HTML, or Hypertext Markup Language, is the standard markup language used for creating web pages. HTML defines the structure and content of a web page, including text, images, and other media. HTML is based on a set of tags and attributes, which are used to define the structure and content of a web page. Here are some of the key elements of HTML:\n\n- Headings and paragraphs\n- Lists and tables\n- Links and images\n- Forms and input fields\n- Styles and CSS\n\nTo get started with HTML, you'll need a text editor and a basic understanding of web development concepts. HTML is a foundational language for web development and is essential for creating static web pages and web applications.",
            },
            {
                "title": "The Benefits of Exercise",
                "summary": "Discover the advantages of regular exercise for your physical and mental health.",
                "content": "Exercise is one of the most important things you can do for your health. Regular exercise has been linked to a range of physical and mental health benefits, including:\n\n- Improved cardiovascular health\n- Lowered risk of chronic disease\n- Increased strength and flexibility\n- Reduced stress and anxiety\n- Improved mood and cognitive function\n\nTo reap the benefits of exercise, aim for at least 30 minutes of moderate-intensity exercise most days of the week. This can include activities like brisk walking, cycling, swimming, or strength training. Find activities you enjoy and make them a regular part of your routine.",
            },
            {
                "title": "The Benefits of Yoga",
                "summary": "Discover the advantages of a regular yoga practice for your physical and mental health.",
                "content": "Yoga is an ancient practice that combines physical postures, breath control, and meditation. Regular yoga practice has been linked to a range of physical and mental health benefits, including:\n\n- Increased flexibility and strength\n- Reduced stress and anxiety\n- Improved balance and coordination\n- Enhanced mood and well-being\n- Lowered blood pressure and heart rate\n- Improved sleep quality\n\nTo get started with yoga, find a class or instructor that fits your needs and level of experience. You can also practice yoga at home using online resources or instructional videos.",
            },
            {
                "title": "The Basics of Machine Learning",
                "summary": "Learn the fundamentals of machine learning and its applications.",
                "content": "Machine learning is a subfield of artificial intelligence that focuses on developing algorithms and models that can learn from and make predictions on data. Machine learning is used in a wide range of applications, including natural language processing, image recognition, and predictive analytics. Here are some of the key concepts in machine learning:\n\n- Supervised learning\n- Unsupervised learning\n- Reinforcement learning\n- Feature engineering\n- Model selection\n\nTo get started with machine learning, you'll need a strong foundation in mathematics, statistics, and programming. There are many online resources and courses available to help you learn the fundamentals of machine learning and start building your own models.",
            },
            {
                "title": "The Benefits of Reading",
                "summary": "Discover the advantages of regular reading for your cognitive function and emotional well-being.",
                "content": "Reading is a valuable activity that has been shown to have a positive impact on cognitive function, emotional well-being, and social relationships. Regular reading has been linked to a range of benefits, including:\n\n- Improved vocabulary and language skills\n- Increased empathy and emotional intelligence\n- Reduced stress and anxiety\n- Enhanced creativity and imagination\n- Improved memory and focus\n\nTo reap the benefits of reading, set aside time each day for reading and choose books that interest and challenge you. You can also join a book club or discussion group to share your thoughts and insights with others.",
            },
            {
                "title": "The Basics of SQL",
                "summary": "Learn the fundamentals of SQL for database management and querying.",
                "content": "SQL, or Structured Query Language, is a programming language used for managing and querying relational databases. SQL is used to create and modify tables, insert and update data, and retrieve data using complex queries. Here are some of the key concepts in SQL:\n\n- Data types and structures\n- Creating tables and indexes\n- Inserting and updating data\n- Selecting and filtering data\n- Joins and subqueries\n\nTo get started with SQL, you'll need a basic understanding of database concepts and a SQL editor or management tool. SQL is an essential skill for data analysts, developers, and anyone working with large amounts of data.",
            },
            {
                "title": "The Importance of Regular Exercise",
                "summary": "Discover why exercise is crucial for your physical and mental health.",
                "content": "Regular exercise has been shown to have numerous benefits for both physical and mental health. Exercise can help you:\n\n- Control your weight\n- Reduce your risk of chronic disease\n- Improve your mood and mental health\n- Increase your energy levels\n- Promote better sleep\n\nTo start an exercise program, find an activity that you enjoy and can realistically fit into your schedule. Aim for at least 150 minutes of moderate-intensity exercise per week, such as brisk walking or cycling. You can also consult with a fitness professional to create a personalized exercise plan.",
            },
            {
                "title": "How to Build a Website with HTML and CSS",
                "summary": "Learn the basics of building a website using HTML and CSS.",
                "content": "HTML and CSS are the building blocks of the web. HTML provides the structure and content of a web page, while CSS is used to style and format the page. Here are some of the key concepts in HTML and CSS:\n\n- HTML tags and elements\n- CSS selectors and properties\n- Box model and layout\n- Responsive design\n\nTo build a website, you'll need a text editor and a web browser. Start by creating a basic HTML page and adding CSS styles to customize the appearance of the page. There are also many online resources and courses available to help you learn HTML and CSS and build more complex websites.",
            },
            {
                "title": "The Benefits of Journaling",
                "summary": "Discover how journaling can improve your mental health and well-being.",
                "content": "Journaling is a simple yet effective practice that involves writing down your thoughts, feelings, and experiences on a regular basis. Research has shown that journaling can have a range of benefits for mental health, including:\n\n- Reduced stress and anxiety\n- Improved mood\n- Increased self-awareness\n- Improved memory and cognitive function\n\nTo start journaling, set aside a few minutes each day to write down your thoughts and feelings. You can use a notebook or journal, or try one of the many journaling apps available. Write freely and without judgment, and use your journal as a tool for self-reflection and growth.",
            },
            {
                "title": "The Basics of Email Marketing",
                "summary": "Learn how to use email marketing to connect with your audience and grow your business.",
                "content": "Email marketing is a powerful tool for businesses of all sizes to connect with their audience and promote their products and services. Here are some of the key concepts in email marketing:\n\n- Building an email list\n- Creating effective email campaigns\n- Segmenting your audience\n- Analyzing your results\n\nTo get started with email marketing, you'll need an email marketing platform and a list of subscribers. Start by creating a welcome email and a regular newsletter, and use segmentation to tailor your messages to specific groups of subscribers. Analyze your results to see what's working and what can be improved.",
            },
            {
                "title": "The Benefits of Learning a New Language",
                "summary": "Discover the advantages of learning a new language for your personal and professional development.",
                "content": "Learning a new language can be a fun and rewarding experience, with a range of benefits for personal and professional development. Here are some of the advantages of learning a new language:\n\n- Improved cognitive function\n- Enhanced cultural understanding\n- Expanded career opportunities\n- Increased creativity\n- Improved communication skills\n\nTo start learning a new language, find a language program or tutor that fits your learning style and schedule. Practice regularly and immerse yourself in the language as much as possible, through reading, listening, and speaking with native speakers.",
            },
            {
                "title": "The Basics of Photography",
                "summary": "Learn the fundamentals of photography and how to capture stunning images.",
                "content": "Photography is the art and science of capturing and creating images using a camera. Here are some of the key concepts in photography:\n\n- Exposure and shutter speed\n- Aperture and depth of field\n- Composition and framing\n- Light and color\n\nTo start taking better photos, familiarize yourself with your camera and its settings. Experiment with different exposures, apertures, and compositions, and practice in a range of lighting conditions. There are also many online resources and courses available to help you learn the fundamentals of photography and improve your skills.",
            },
            {
                "title": "The Importance of Cybersecurity",
                "summary": "Learn why cybersecurity is crucial in today's digital world.",
                "content": "Cybersecurity is the practice of protecting electronic devices, networks, and sensitive information from theft, damage, or unauthorized access. As more of our lives move online, cybersecurity has become increasingly important. Here are some of the reasons why:\n\n- Preventing data breaches and identity theft\n- Protecting against cyber attacks and malware\n- Ensuring privacy and confidentiality\n- Complying with laws and regulations\n\nTo improve your cybersecurity, use strong passwords, keep your software and devices up to date, and avoid sharing sensitive information online. You can also consider using antivirus software or a virtual private network (VPN) for added protection.",
            },
            {
                "title": "The Benefits of Mindfulness",
                "summary": "Discover how mindfulness can improve your mental and physical health.",
                "content": "Mindfulness is the practice of paying attention to the present moment, without judgment. It can be a powerful tool for reducing stress and anxiety, improving focus and concentration, and enhancing overall well-being. Here are some of the benefits of mindfulness:\n\n- Reduced stress and anxiety\n- Improved sleep\n- Increased self-awareness\n- Enhanced emotional regulation\n- Reduced symptoms of depression\n\nTo start practicing mindfulness, try incorporating it into your daily routine. You can try mindfulness meditation, mindful breathing, or simply paying attention to your surroundings with curiosity and openness.",
            },
            {
                "title": "The Benefits of HIIT Workouts",
                "summary": "Learn how high-intensity interval training (HIIT) can help you get in shape and improve your health.",
                "content": "HIIT workouts involve short bursts of intense exercise followed by periods of rest or low-intensity activity. This type of training can be a highly effective way to burn calories, build muscle, and improve cardiovascular health. Here are some of the benefits of HIIT workouts:\n\n- Increased calorie burn and fat loss\n- Improved cardiovascular fitness\n- Enhanced metabolic function\n- Increased muscle strength and endurance\n\nTo start incorporating HIIT workouts into your fitness routine, try incorporating short bursts of high-intensity exercise into your regular workouts, such as sprinting or jumping jacks. You can also try a dedicated HIIT workout class or video.",
            },
            {
                "title": "The Benefits of Volunteering",
                "summary": "Discover how volunteering can benefit both yourself and your community.",
                "content": "Volunteering can be a powerful way to give back to your community while also benefiting yourself. Here are some of the benefits of volunteering:\n\n- Increased sense of purpose and fulfillment\n- Improved mental and physical health\n- Enhanced social connections and networks\n- Expanded skill set and experience\n\nTo start volunteering, find a cause or organization that aligns with your interests and values. You can also consider reaching out to your local volunteer center or community service organization for opportunities.",
            },
            {
                "title": "The Search for Extraterrestrial Life",
                "summary": "Discover the ongoing efforts to find life beyond Earth.",
                "content": "For decades, scientists have been searching for signs of life beyond our planet. While we have yet to find conclusive evidence, the search continues. Here are some of the ways that scientists are searching for extraterrestrial life:\n\n- Scanning the skies for radio signals or other forms of communication\n- Studying the atmospheres of exoplanets for signs of life-sustaining conditions\n- Searching for microbial life in extreme environments on Earth, such as hot springs or deep-sea hydrothermal vents\n\nThe search for extraterrestrial life is a complex and challenging endeavor, but it holds the potential to revolutionize our understanding of the universe and our place in it.",
            },
            {
                "title": "The Physics of Time Travel",
                "summary": "Explore the possibilities and limitations of time travel according to current physics theories.",
                "content": "Time travel is a popular science fiction concept, but is it possible according to the laws of physics? While time travel remains a topic of speculation and debate among physicists, there are some theories and limitations to consider. Here are some key points:\n\n- According to Einstein's theory of relativity, time can be stretched or compressed depending on the observer's velocity and position in space.\n- The theory of general relativity also allows for the possibility of closed timelike curves, which could allow for time travel under certain conditions.\n- However, there are many paradoxes and inconsistencies that arise when considering the possibility of time travel, such as the grandfather paradox.\n\nWhile the physics of time travel remains uncertain, it continues to inspire new ideas and theories in the field of physics.",
            },
            {
                "title": "The Beauty of Fractals",
                "summary": "Learn about the fascinating world of fractals and their mathematical beauty.",
                "content": "Fractals are complex, self-similar patterns that repeat at different scales, and they are found throughout nature and in mathematics. From the branching patterns of trees to the intricate details of snowflakes, fractals have inspired artists, scientists, and mathematicians alike. Here are some key concepts and examples of fractals:\n\n- Fractals are created through mathematical equations, and can be generated using computer programs or by hand.\n- Some of the most famous fractals include the Mandelbrot set, the Koch snowflake, and the Sierpinski triangle.\n- Fractals have applications in many fields, such as computer graphics, ecology, and finance.\n\nThe beauty and complexity of fractals continue to inspire new ideas and discoveries in mathematics and beyond.",
            },
            {
                "title": "The Search for Dark Matter",
                "summary": "Discover the ongoing efforts to understand the mysterious substance known as dark matter.",
                "content": "Dark matter is a mysterious substance that is believed to make up a large portion of the universe's mass, yet it cannot be directly observed or detected. The search for dark matter is a major focus of modern astrophysics, and scientists are using a variety of methods to try and understand this enigmatic substance. Here are some key points:\n\n- Dark matter is thought to interact only weakly with other matter, which makes it difficult to detect.\n- Scientists are searching for dark matter using a variety of methods, such as observing the motions of galaxies and looking for signals in underground detectors.\n- The discovery of dark matter could have profound implications for our understanding of the universe and the laws of physics.\n\nWhile the search for dark matter is ongoing, it continues to be a fascinating and important area of research in astrophysics.",
            },
            {
                "content": "Just learned about the latest breakthrough in quantum computing! Exciting times ahead for technology. 🚀 #STEM #quantum #computing",
            },
            {
                "content": "Did you know that the closest galaxy to our Milky Way is the Canis Major Dwarf Galaxy, located about 25,000 light-years away? 🌌 #spacefacts #astronomy",
            },
            {
                "content": "The search for extraterrestrial life continues! Scientists are now exploring the possibility of life on moons like Enceladus and Europa. 🪐 #astrobiology #spaceexploration",
            },
            {
                "content": "STEM education is crucial for preparing the next generation of problem solvers and innovators. Let's inspire more students to pursue careers in science, technology, engineering, and math! 🧑‍🔬🧑‍💻🧑‍🔧🧑‍🚀 #STEMeducation #futureinnovators",
            },
            {
                "content": "From black holes to gravitational waves, the universe never ceases to amaze us with its mysteries. We're lucky to live in a time when technology allows us to explore these wonders like never before. 🌌 #astrophysics #cosmology #science",
            },
        ],
    )
)
random.shuffle(SAMPLE_POSTS)
_index = 0
_n = len(SAMPLE_POSTS)


def any_post():
    """Returns one of SAMPLE_POSTS.

    The order is randomized at test initialization then accessed linearly
    to avoid duplication during a test (which could occasionally happen
    with `random.choice`)."""
    global _index
    post = SAMPLE_POSTS[_index % _n]
    _index += 1
    return post
