# Generated by Django 3.2.4 on 2022-03-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_app_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='changelog',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='created',
            new_name='created_at',
        ),
    ]
