# Generated by Django 3.2.4 on 2022-04-28 16:46

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220427_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='accent_color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=18, samples=[('#ee4545', 'red'), ('#0e70b8', 'blue'), ('#16b06b', 'green'), ('#823dae', 'purple'), ('#e13255', 'pink'), ('#fdf472', 'yellow'), ('#d86900', 'orange'), ('#636363', 'grey')]),
        ),
        migrations.AlterField(
            model_name='app',
            name='primary_color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=18, samples=[('#ee4545', 'red'), ('#0e70b8', 'blue'), ('#16b06b', 'green'), ('#823dae', 'purple'), ('#e13255', 'pink'), ('#fdf472', 'yellow'), ('#d86900', 'orange'), ('#636363', 'grey')]),
        ),
        migrations.AlterField(
            model_name='article',
            name='accent_color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=18, samples=[('#ee4545', 'red'), ('#0e70b8', 'blue'), ('#16b06b', 'green'), ('#823dae', 'purple'), ('#e13255', 'pink'), ('#fdf472', 'yellow'), ('#d86900', 'orange'), ('#636363', 'grey')]),
        ),
        migrations.AlterField(
            model_name='article',
            name='primary_color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=18, samples=[('#ee4545', 'red'), ('#0e70b8', 'blue'), ('#16b06b', 'green'), ('#823dae', 'purple'), ('#e13255', 'pink'), ('#fdf472', 'yellow'), ('#d86900', 'orange'), ('#636363', 'grey')]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='accent_color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=18, samples=[('#ee4545', 'red'), ('#0e70b8', 'blue'), ('#16b06b', 'green'), ('#823dae', 'purple'), ('#e13255', 'pink'), ('#fdf472', 'yellow'), ('#d86900', 'orange'), ('#636363', 'grey')]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='primary_color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=18, samples=[('#ee4545', 'red'), ('#0e70b8', 'blue'), ('#16b06b', 'green'), ('#823dae', 'purple'), ('#e13255', 'pink'), ('#fdf472', 'yellow'), ('#d86900', 'orange'), ('#636363', 'grey')]),
        ),
    ]
