# Generated by Django 4.0.4 on 2022-05-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220501_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_script',
            field=models.TextField(blank=True, help_text='Any post-specific scripts or styles that need to be added at the end of the <body> HTML tag.', null=True),
        ),
    ]
