# Generated by Django 4.0.4 on 2022-05-04 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0007_githublanguage_created_at'),
        ('main', '0014_article_content_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app', to='github.githubrepository'),
        ),
    ]
