# Generated by Django 4.0.4 on 2022-05-04 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0007_githublanguage_created_at'),
        ('main', '0015_app_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='repository',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app', to='github.githubrepository'),
        ),
    ]
