# Generated by Django 4.0.4 on 2022-05-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_app_code_languages_app_primary_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppImage',
        ),
    ]
