# Generated by Django 4.0.4 on 2022-05-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_delete_appimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hero_aspect_ratio',
        ),
        migrations.RemoveField(
            model_name='article',
            name='html_head',
        ),
    ]
