# Generated by Django 4.0.4 on 2022-05-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_article_hero_aspect_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hero_banner',
            field=models.CharField(blank=True, choices=[('contain', 'contain'), ('cover', 'cover')], default='contain', help_text='contain: border around image. cover: full-width primary color', max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='hero_css',
            field=models.CharField(blank=True, choices=[('contain', 'contain'), ('cover', 'cover')], default='cover', help_text='CSS class', max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview_image_css',
            field=models.CharField(blank=True, choices=[('contain', 'contain'), ('cover', 'cover')], default='cover', help_text='CSS class', max_length=80),
        ),
    ]
