# Generated by Django 4.0.4 on 2022-05-23 11:16

from django.db import migrations
import main.forms.filename
import main.forms.sanitized_filefield


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_article_format_alter_blog_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=main.forms.sanitized_filefield.SanitizedFileField(blank=True, quality=75, size=[800, 800], upload_to=main.forms.filename.RandomFilename('app/', filename_attrs=[], filename_literals=[])),
        ),
    ]
