# Generated by Django 4.1.5 on 2023-04-08 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_remove_article_is_featured_remove_blog_is_featured_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="changelog",
            options={},
        ),
        migrations.RenameField(
            model_name="article",
            old_name="modified",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="modified",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="changelog",
            old_name="modified",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="modified",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="app",
            old_name="date_published",
            new_name="published_at",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="updated",
            new_name="published_at",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="updated",
            new_name="published_at",
        ),
        migrations.RenameField(
            model_name="changelog",
            old_name="date",
            new_name="published_at",
        ),
        migrations.RemoveField(
            model_name="changelog",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="project",
            name="created",
        ),
        migrations.AddField(
            model_name="about",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="app",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="apptype",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="host",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="link",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="messageoftheday",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="note",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="note",
            name="published_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="relatedfile",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="webapp",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
