# Generated by Django 3.2.4 on 2022-01-26 17:08

from django.db import migrations, models
import webmentions_tester.models


class Migration(migrations.Migration):

    dependencies = [
        ('webmentions_tester', '0002_alter_temporarymention_submission_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarymention',
            name='submission_time',
            field=models.DateTimeField(default=webmentions_tester.models._submission_time),
        ),
    ]
