# Generated by Django 3.2.4 on 2022-04-11 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webmentions_tester', '0003_alter_temporarymention_submission_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temporarymention',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='temporarymention',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
