# Generated by Django 3.2.4 on 2022-02-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidWurd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wurd', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'ordering': ['wurd'],
            },
        ),
        migrations.CreateModel(
            name='Wurd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wurd', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
    ]
