# Generated by Django 3.2.4 on 2022-04-11 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wurdle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wurd',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
