# Generated by Django 4.1.5 on 2023-04-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wurdle", "0002_alter_wurd_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="validwurd",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="wurd",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
