# Generated by Django 4.1.5 on 2023-04-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0004_auto_20220411_1037"),
    ]

    operations = [
        migrations.AddField(
            model_name="webmailmessage",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
