# Generated by Django 4.1.5 on 2023-04-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_webmailmessage_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='webmailmessage',
            name='has_been_read',
            field=models.BooleanField(default=False),
        ),
    ]
