# Generated by Django 6.1 on 2026-09-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0006_webmailmessage_has_been_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="webmailmessage",
            name="recaptcha_verified",
            field=models.BooleanField(default=False),
        ),
    ]
