import { PostPreview } from "@/components/data/types";
import { MediaFile } from "@/components/media/common";

export const LoremIpsum =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque mattis, orci vel congue vehicula, velit metus cursus nisl, sed condimentum elit libero id diam. Cras pharetra quam vel nisl gravida blandit. Aliquam lorem tellus, mattis at mi dictum, interdum dictum dolor. Ut tempus mauris ut vulputate efficitur. Sed est ligula, aliquam nec porta non, dictum id neque. Donec ornare, nunc ac hendrerit pretium, elit magna sagittis dolor, vel aliquam ipsum lorem ac lorem. Quisque dignissim, dui nec facilisis euismod, lectus leo posuere ligula, sed tempus eros ante ut mi.";

export const SampleMedia: MediaFile[] = [
  {
    url: "/media/related/2025/45f545.jpg",
    thumbnail_url: "/media/related/2025/45f545-thumb.webp",
    type: "image",
    name: "related/2022/45f545.jpg",
    description: "",
    fit: null,
  },
  {
    url: "/media/related/2025/ab909e.jpg",
    thumbnail_url: "/media/related/2025/ab909e-thumb.webp",
    type: "image",
    name: "related/2022/ab909e.jpg",
    description: "",
    fit: null,
  },
  {
    url: "/media/related/2025/3466a3.jpg",
    thumbnail_url: "/media/related/2025/3466a3-thumb.webp",
    type: "image",
    name: "related/2022/3466a3.jpg",
    description: "",
    fit: null,
  },
];

export const SamplePosts: PostPreview[] = [
  {
    post_type: "post",
    title: "Tailwind Prose",
    url: "/posts/202504028a1/",
    is_published: true,
    published_at: "2025-04-02T17:21:01.768Z",
    theme: null,
    hero_embedded_url: null,
    hero_image: null,
    content_html: "Typography check",
    content_script: "",
    links: [],
    files: [],
    tags: [],
    is_preview: true,
  },
  {
    post_type: "post",
    title: null,
    url: "/posts/20250301712/",
    is_published: true,
    published_at: "2025-03-01T16:42:09Z",
    theme: {
      muted: "#0E70B8",
      vibrant: "#FDF472",
    },
    hero_embedded_url: null,
    hero_image: null,
    content_html:
      "<p>Hosting for this site is now provided by a European company instead of Amazon.</p>\n\n<p>It&#8217;s an extremely minor thing, but it is a thing nonetheless. 🇺🇦🇪🇺🇬🇧</p>\n",
    content_script: "",
    links: [],
    files: [],
    tags: [],
    is_preview: false,
  },
  {
    post_type: "post",
    title: null,
    url: "/posts/2024122259f/",
    is_published: true,
    published_at: "2024-12-22T14:55:33Z",
    theme: null,
    hero_embedded_url: null,
    hero_image: null,
    content_html:
      '<p>A year of incrementally learning Polyphia tunes: <a href="https://www.youtube.com/watch?v=Z5WudJ53zGs" >youtube</a></p>\n',
    content_script: null,
    links: [],
    files: [
      {
        url: "/media/related/2025/68490e.jpg",
        thumbnail_url: "/media/related/2025/68490e-thumb.webp",
        type: "image",
        name: "Capture.JPG",
        description: "",
        fit: null,
      },
    ],
    tags: [],
    is_preview: false,
  },
  {
    post_type: "post",
    title: null,
    url: "/posts/20241106d9e/",
    is_published: true,
    published_at: "2024-11-06T07:36:05Z",
    theme: null,
    hero_embedded_url: null,
    hero_image: null,
    content_html: "<p>🤢</p>\n",
    content_script: null,
    links: [],
    files: [],
    tags: [],
    is_preview: false,
  },
  {
    post_type: "post",
    title: null,
    url: "/posts/2024103072e/",
    is_published: true,
    published_at: "2024-10-30T22:17:36Z",
    theme: null,
    hero_embedded_url: null,
    hero_image: null,
    content_html: "<p>Jigsaw pumpkin 🎃</p>\n",
    content_script: null,
    links: [],
    files: [
      {
        url: "/media/related/2025/e0f6f8.jpeg",
        thumbnail_url: "/media/related/2025/e0f6f8-thumb.webp",
        type: "image",
        name: "uxSbl.jpeg",
        description: "",
        fit: null,
      },
      {
        url: "/media/related/2025/2188b0.jpeg",
        thumbnail_url: "/media/related/2025/2188b0-thumb.webp",
        type: "image",
        name: "9ffkm.jpeg",
        description: "",
        fit: null,
      },
    ],
    tags: [
      {
        name: "halloween",
      },
      {
        name: "jigsaw",
      },
      {
        name: "pumpkin",
      },
      {
        name: "art",
      },
    ],
    is_preview: false,
  },
  {
    post_type: "app",
    title: "Treefactor",
    url: "/apps/webapp-treefactor/",
    is_published: true,
    published_at: "2024-10-09T12:41:16.434Z",
    theme: null,
    hero_embedded_url: null,
    hero_image: null,
    content_html: "<p></p>\n",
    content_script: null,
    links: [],
    files: [],
    tags: [],
    is_preview: false,
  },
  {
    post_type: "changelog",
    title: "Microformats Reader 1.0.275",
    url: "/changelog/microformats-reader-1-0-275/",
    is_published: true,
    published_at: "2024-09-17T09:43:00Z",
    theme: null,
    hero_embedded_url: null,
    hero_image: null,
    content_html:
      "Many more microformat tags supported, now available for Firefox + Chrome.",
    content_script: null,
    links: [],
    files: [],
    tags: [],
    is_preview: true,
  },
  {
    post_type: "post",
    title: null,
    url: "/posts/20240330e2f/",
    is_published: true,
    published_at: "2024-03-30T10:14:33Z",
    theme: null,
    hero_embedded_url: null,
    hero_image: null,
    content_html: "<p>The continuing saga of Holiday Cat</p>\n",
    content_script: null,
    links: [],
    files: [
      {
        url: "/media/related/2025/8a36f4.jpg",
        thumbnail_url: "/media/related/2025/8a36f4-thumb.webp",
        type: "image",
        name: "PXL_20240328_205909119.PORTRAIT.jpg",
        description: "",
        fit: null,
      },
    ],
    tags: [],
    is_preview: false,
  },
  {
    post_type: "app",
    title: "Clocks",
    url: "/apps/webapp-clocks/",
    is_published: true,
    published_at: "2024-03-01T18:28:46.258Z",
    theme: null,
    hero_embedded_url: null,
    hero_image: null,
    content_html: "<p></p>\n",
    content_script: null,
    links: [],
    files: [],
    tags: [],
    is_preview: false,
  },
  {
    post_type: "app",
    title: "Palette",
    url: "/apps/webapp-palette/",
    is_published: true,
    published_at: "2024-02-29T12:03:48.136Z",
    theme: null,
    hero_embedded_url: null,
    hero_image: null,
    content_html: "Simple viewer for a colour palette.",
    content_script: null,
    links: [],
    files: [],
    tags: [],
    is_preview: true,
  },
  {
    post_type: "app",
    title: "Orbitals",
    url: "/apps/webapp-orbitals/",
    is_published: true,
    published_at: "2024-02-28T15:47:18.164Z",
    theme: null,
    hero_embedded_url: null,
    hero_image: null,
    content_html: "<p></p>\n",
    content_script: null,
    links: [],
    files: [],
    tags: [],
    is_preview: false,
  },
  {
    post_type: "changelog",
    title: "django-wm 4.1.1",
    url: "/changelog/django-wm-4-1-1/",
    is_published: true,
    published_at: "2024-02-10T15:14:11Z",
    theme: null,
    hero_embedded_url: null,
    hero_image: null,
    content_html:
      "Added Webmention.has_been_read field and new settings for enabling webmentions depending on source/target domain.",
    content_script: null,
    links: [],
    files: [],
    tags: [],
    is_preview: true,
  },
  {
    post_type: "changelog",
    title: "django-wm 4.0.4",
    url: "/changelog/django-wm-4-0-4/",
    is_published: true,
    published_at: "2024-02-02T15:13:22Z",
    theme: null,
    hero_embedded_url: null,
    hero_image: null,
    content_html: "Resolves #53: Compatibility with dependency mf2py>=2.0.",
    content_script: null,
    links: [],
    files: [],
    tags: [],
    is_preview: true,
  },
  {
    post_type: "post",
    title: null,
    url: "/posts/2023121542a/",
    is_published: true,
    published_at: "2023-12-15T22:31:23Z",
    theme: null,
    hero_embedded_url: null,
    hero_image: null,
    content_html: "<p>Holiday cat, I guess</p>\n",
    content_script: null,
    links: [],
    files: [
      {
        url: "/media/related/2025/16f8f6.jpg",
        thumbnail_url: "/media/related/2025/16f8f6-thumb.webp",
        type: "image",
        name: "PXL_20231221_222657475.jpg",
        description: "",
        fit: null,
      },
    ],
    tags: [],
    is_preview: false,
  },
  {
    post_type: "post",
    title: null,
    url: "/posts/2023103061f/",
    is_published: true,
    published_at: "2023-10-30T18:14:00Z",
    theme: null,
    hero_embedded_url: null,
    hero_image: null,
    content_html:
      '<p>3D printed cat with a hat made from old jeans.</p>\n\n<p>Model by Toonz Factory: <a href="https://www.thingiverse.com/thing:6236328" >thingiverse/6236328</a></p>\n',
    content_script: null,
    links: [],
    files: [
      {
        url: "/media/related/2025/fe7cae.jpg",
        thumbnail_url: "/media/related/2025/fe7cae-thumb.webp",
        type: "image",
        name: "jpeg",
        description: "",
        fit: null,
      },
    ],
    tags: [
      {
        name: "halloween",
      },
    ],
    is_preview: false,
  },
  {
    post_type: "app",
    title: "beatonma.org",
    url: "/apps/beatonmaorg/",
    is_published: true,
    published_at: "2023-06-28T20:32:40Z",
    theme: {
      muted: "#131313",
      vibrant: "#E13255",
    },
    hero_embedded_url: null,
    hero_image: null,
    content_html: "This website",
    content_script: null,
    links: [
      {
        url: "https://github.com/beatonma/beatonma.org",
        description: "source",
        host: "Github",
        icon: null,
      },
    ],
    files: [],
    tags: [
      {
        name: "django",
      },
      {
        name: "sass",
      },
      {
        name: "docker",
      },
      {
        name: "gulp",
      },
      {
        name: "typescript",
      },
      {
        name: "blog",
      },
    ],
    is_preview: true,
  },
  {
    post_type: "changelog",
    title: "django-wm 4.0.2",
    url: "/changelog/django-wm-4-0-2/",
    is_published: true,
    published_at: "2023-05-27T15:12:48Z",
    theme: null,
    hero_embedded_url: null,
    hero_image: null,
    content_html:
      "Resolves #50: broken search field on QuotableAdmin.\nAdded tests for admin pages to avoid that sort of thing happening again.\nMinor touch-ups for the admin pages.\nSource and target URL fields are now read-only.\nAdded appropriate search fields and list…",
    content_script: null,
    links: [],
    files: [],
    tags: [],
    is_preview: true,
  },
  {
    post_type: "changelog",
    title: "django-wm 4.0.1",
    url: "/changelog/django-wm-4-0-1/",
    is_published: true,
    published_at: "2022-12-22T15:12:17Z",
    theme: null,
    hero_embedded_url: null,
    hero_image: null,
    content_html:
      "Added management command mentions_reverify [filters ...] [--all]\nAllows you to reprocess received Webmentions to see if they are still ‘live’.\nAccepts a space-separated list of field=value queryset filters, or --all to reprocess all of them.\nAdded ma…",
    content_script: null,
    links: [],
    files: [],
    tags: [],
    is_preview: true,
  },
  {
    post_type: "changelog",
    title: "django-wm 4.0.0",
    url: "/changelog/django-wm-4-0-0/",
    is_published: true,
    published_at: "2022-11-25T15:11:35Z",
    theme: null,
    hero_embedded_url: null,
    hero_image: null,
    content_html:
      "This update alters fields on MentionableMixin so you will need to run makemigrations and migrate after upgrading!\r\nMentionableMixin:\r\nallow_outgoing_webmentions default now configurable via settings.WEBMENTIONS_ALLOW_OUTGOING_DEFAULT.\r\nRemoved slug fiel…",
    content_script: null,
    links: [],
    files: [],
    tags: [],
    is_preview: true,
  },
  {
    post_type: "changelog",
    title: "django-wm 3.1.1",
    url: "/changelog/django-wm-3-1-1/",
    is_published: true,
    published_at: "2022-10-26T15:10:54Z",
    theme: null,
    hero_embedded_url: null,
    hero_image: null,
    content_html:
      "Fixes #43: outgoing webmention being resubmitted continuously.",
    content_script: null,
    links: [],
    files: [],
    tags: [],
    is_preview: true,
  },
  {
    post_type: "changelog",
    title: "django-wm 3.1.0",
    url: "/changelog/django-wm-3-1-0/",
    is_published: true,
    published_at: "2022-10-06T15:09:43Z",
    theme: null,
    hero_embedded_url: null,
    hero_image: null,
    content_html:
      "Resolves #38: Revalidate target URLs when handling pending mentions\r\nShould be unnecessary generally (they are also validated at discovery time when parsed from HTML) but important if validation checks are updated.\r\nResolves #41: Find correct endpoint …",
    content_script: null,
    links: [],
    files: [],
    tags: [],
    is_preview: true,
  },
  {
    post_type: "changelog",
    title: "django-wm 3.0.0",
    url: "/changelog/django-wm-3-0-0/",
    is_published: true,
    published_at: "2022-09-29T15:07:23Z",
    theme: null,
    hero_embedded_url: null,
    hero_image: null,
    content_html:
      "Upgrade warning\nIf upgrading from an older version please be aware of these changes:\nUnused MentionableMixin.allow_incoming_webmentions field has been removed.\nAny existing instances of PendingIncomingWebmention and PendingOutgoingContent will be del…",
    content_script: null,
    links: [],
    files: [],
    tags: [
      {
        name: "anchor",
      },
    ],
    is_preview: true,
  },
  {
    post_type: "changelog",
    title: "beatonma.org 2.0",
    url: "/changelog/beatonma-org-2-0/",
    is_published: true,
    published_at: "2022-05-19T18:41:15Z",
    theme: null,
    hero_embedded_url: null,
    hero_image: null,
    content_html: "Fitter. Happier. More productive.",
    content_script: null,
    links: [],
    files: [],
    tags: [],
    is_preview: true,
  },
  {
    post_type: "app",
    title: "Subcircuit Switcher",
    url: "/apps/webapp-subcircuit-switcher/",
    is_published: true,
    published_at: "2022-05-14T18:45:20.789Z",
    theme: null,
    hero_embedded_url: null,
    hero_image: null,
    content_html:
      "Simulation of a 4PDT switch for moving a subcircuit between two parent circuits.",
    content_script: null,
    links: [],
    files: [],
    tags: [],
    is_preview: true,
  },
];
