# Generated by Django 5.2 on 2025-05-04 17:36

import uuid

import colorfield.fields
import common.microformats
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import main.forms.filename
import main.models.mixins.styleable_svg
import main.storage
import mentions.models.mixins.mentionable
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("main", "0001_initial_squashed_0004_auto_20220328_1846"),
        ("main", "0002_app_description"),
        ("main", "0003_auto_20220330_1009"),
        ("main", "0004_auto_20220330_1048"),
        ("main", "0005_auto_20220330_1101"),
        ("main", "0006_auto_20220330_1310"),
        ("main", "0007_auto_20220401_1049"),
        ("main", "0008_auto_20220406_1924"),
        ("main", "0009_auto_20220411_1008"),
        ("main", "0010_auto_20220411_1037"),
        ("main", "0011_auto_20220427_1749"),
        ("main", "0012_auto_20220428_1646"),
        ("main", "0013_auto_20220501_1724"),
        ("main", "0014_article_content_script"),
        ("main", "0015_app_repository"),
        ("main", "0016_alter_app_repository"),
        ("main", "0017_remove_app_code_languages_app_primary_language"),
        ("main", "0018_delete_appimage"),
        ("main", "0019_remove_article_hero_aspect_ratio_and_more"),
        ("main", "0020_article_hero_banner_alter_article_hero_css_and_more"),
        ("main", "0021_rename_hero_banner_article_hero_banner_css"),
        ("main", "0022_rename_app_article_apps"),
        ("main", "0023_about"),
        ("main", "0024_relatedfile_original_filename_alter_app_icon_and_more"),
        ("main", "0025_alter_app_icon_alter_article_hero_image_and_more"),
        ("main", "0026_alter_article_format_alter_blog_format_and_more"),
        ("main", "0027_alter_app_icon"),
        ("main", "0028_remove_app_allow_incoming_webmentions_and_more"),
        ("main", "0029_alter_article_tweet_alter_blog_tweet_and_more"),
        ("main", "0030_alter_article_tweet_alter_blog_tweet_and_more"),
        ("main", "0031_messageoftheday_display_from_and_more"),
        ("main", "0032_remove_article_tweet_remove_article_tweet_id_and_more"),
        ("main", "0033_remove_article_is_featured_remove_blog_is_featured_and_more"),
        ("main", "0034_alter_changelog_options_and_more"),
        ("main", "0035_alter_app_published_at_alter_article_published_at_and_more"),
        ("main", "0036_rename_primary_color_app_color_muted_and_more"),
        ("main", "0037_alter_app_color_muted_alter_app_color_vibrant_and_more"),
        ("main", "0038_remove_app_color_on_muted_and_more"),
        ("main", "0039_rename_display_from_messageoftheday_public_from_and_more"),
        ("main", "0040_themeoverride"),
        ("main", "0041_alter_themeoverride_options"),
        ("main", "0042_alter_changelog_app"),
        ("main", "0043_alter_app_app_type"),
        ("main", "0044_alter_changelog_options"),
        ("main", "0045_alter_app_color_muted_alter_app_color_vibrant_and_more"),
        ("main", "0046_alter_link_description"),
        ("main", "0047_apieditable_webpost_and_relatedfile"),
        ("main", "0048_apieditable_20231128_1341"),
        ("main", "0049_apieditable_20231128_1342"),
        ("main", "0050_alter_relatedfile_description"),
        ("main", "0051_alter_note_content"),
        ("main", "0052_webapp_inherit_site_theme"),
        ("main", "0053_webapp_resource"),
        ("main", "0054_alter_relatedfile_file_storage"),
        ("main", "0055_alter_article_hero_image_alter_relatedfile_file"),
        ("main", "0056_alter_webapp_options_alter_webappresource_options_and_more"),
        ("main", "0057_alter_relatedfile_file"),
        ("main", "0058_relatedfile_type"),
        ("main", "0059_app_extends_webpost"),
        ("main", "0060_app_format"),
        ("main", "0061_relatedfile_fit_thumbnail"),
        ("main", "0062_0076_squashed_posts_remake"),
        ("main", "0063_remake_sitehcard"),
        ("main", "0064_alter_link_options_link_sort_order"),
        ("main", "0065_apppost_widget_style"),
        ("main", "0066_editable_slug"),
        ("main", "0067_preview_formatting"),
        ("main", "0068_alter_aboutpost_slug_alter_post_slug"),
        ("main", "0069_pointsofinterest"),
        ("main", "0070_link_label"),
        ("main", "0071_delete_about_remove_app_app_type_and_more"),
        ("main", "0072_delete_project"),
        ("main", "0073_remove_webappresource_webapp_delete_webapp_and_more"),
    ]

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("github", "0004_auto_20220406_1924"),
        ("github", "0007_githublanguage_created_at"),
        ("github", "0014_alter_cachedresponse_data"),
        ("taggit", "0003_taggeditem_add_unique_index"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon_file",
                    models.FileField(
                        blank=True,
                        help_text="SVG icon",
                        upload_to="icon/",
                        validators=[main.models.mixins.styleable_svg.validate_svg],
                    ),
                ),
                (
                    "icon_svg",
                    models.CharField(
                        blank=True, help_text="<svg> element", max_length=8192
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "domain",
                    models.CharField(
                        help_text="Unique url pattern used for parsing",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MessageOfTheDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=64, null=True)),
                ("content", models.TextField()),
                (
                    "is_published",
                    models.BooleanField(default=True, help_text="Publicly visible"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("public_from", models.DateTimeField(blank=True, null=True)),
                ("public_until", models.DateTimeField(blank=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name_plural": "Messages of the Day",
            },
        ),
        migrations.CreateModel(
            name="ThemeOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "is_published",
                    models.BooleanField(default=True, help_text="Publicly visible"),
                ),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "color_muted",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        image_field=None,
                        max_length=25,
                        samples=[
                            ("#ee4545", "#ee4545"),
                            ("#0e70b8", "#0e70b8"),
                            ("#16b06b", "#16b06b"),
                            ("#823dae", "#823dae"),
                            ("#e13255", "#e13255"),
                            ("#fdf472", "#fdf472"),
                            ("#d86900", "#d86900"),
                            ("#636363", "#636363"),
                            ("#ff6d60", "#ff6d60"),
                            ("#f7d060", "#f7d060"),
                            ("#f3e99f", "#f3e99f"),
                            ("#98d8aa", "#98d8aa"),
                            ("#3c486b", "#3c486b"),
                            ("#f0f0f0", "#f0f0f0"),
                            ("#f9d949", "#f9d949"),
                            ("#f45050", "#f45050"),
                            ("#4d455d", "#4d455d"),
                            ("#e96479", "#e96479"),
                            ("#f5e9cf", "#f5e9cf"),
                            ("#7db9b6", "#7db9b6"),
                            ("#0a4d68", "#0a4d68"),
                            ("#088395", "#088395"),
                            ("#05bfdb", "#05bfdb"),
                            ("#00ffca", "#00ffca"),
                            ("#2c3333", "#2c3333"),
                            ("#2e4f4f", "#2e4f4f"),
                            ("#0e8388", "#0e8388"),
                            ("#cbe4de", "#cbe4de"),
                            ("#181823", "#181823"),
                            ("#537fe7", "#537fe7"),
                            ("#c0eef2", "#c0eef2"),
                            ("#e9f8f9", "#e9f8f9"),
                            ("#483838", "#483838"),
                            ("#42855b", "#42855b"),
                            ("#90b77d", "#90b77d"),
                            ("#d2d79f", "#d2d79f"),
                        ],
                    ),
                ),
                (
                    "color_vibrant",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        image_field=None,
                        max_length=25,
                        samples=[
                            ("#ee4545", "#ee4545"),
                            ("#0e70b8", "#0e70b8"),
                            ("#16b06b", "#16b06b"),
                            ("#823dae", "#823dae"),
                            ("#e13255", "#e13255"),
                            ("#fdf472", "#fdf472"),
                            ("#d86900", "#d86900"),
                            ("#636363", "#636363"),
                            ("#ff6d60", "#ff6d60"),
                            ("#f7d060", "#f7d060"),
                            ("#f3e99f", "#f3e99f"),
                            ("#98d8aa", "#98d8aa"),
                            ("#3c486b", "#3c486b"),
                            ("#f0f0f0", "#f0f0f0"),
                            ("#f9d949", "#f9d949"),
                            ("#f45050", "#f45050"),
                            ("#4d455d", "#4d455d"),
                            ("#e96479", "#e96479"),
                            ("#f5e9cf", "#f5e9cf"),
                            ("#7db9b6", "#7db9b6"),
                            ("#0a4d68", "#0a4d68"),
                            ("#088395", "#088395"),
                            ("#05bfdb", "#05bfdb"),
                            ("#00ffca", "#00ffca"),
                            ("#2c3333", "#2c3333"),
                            ("#2e4f4f", "#2e4f4f"),
                            ("#0e8388", "#0e8388"),
                            ("#cbe4de", "#cbe4de"),
                            ("#181823", "#181823"),
                            ("#537fe7", "#537fe7"),
                            ("#c0eef2", "#c0eef2"),
                            ("#e9f8f9", "#e9f8f9"),
                            ("#483838", "#483838"),
                            ("#42855b", "#42855b"),
                            ("#90b77d", "#90b77d"),
                            ("#d2d79f", "#d2d79f"),
                        ],
                    ),
                ),
                ("public_from", models.DateTimeField(blank=True, null=True)),
                ("public_until", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=256)),
            ],
            options={
                "ordering": [
                    "-is_published",
                    "public_from",
                    "public_until",
                    "-created_at",
                ],
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("url", models.URLField(max_length=512)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("source", "Source"),
                            ("install", "Install"),
                            ("download", "Download"),
                            ("webapp", "Webapp"),
                            ("link", "Link"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="main.host",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("url", "content_type", "object_id"),
                        name="unique_url_per_target",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RelatedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    main.forms.sanitized_filefield.SanitizedFileField(
                        blank=True,
                        quality=75,
                        size=[2560, 1440],
                        upload_to=main.forms.filename.RandomFilename(
                            "related/%Y/",
                            filename_attrs=["description"],
                            filename_literals=[],
                        ),
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="File content description",
                        max_length=140,
                        null=True,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(editable=False, max_length=1024, null=True),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "api_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="relatedfile",
            name="api_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="relatedfile",
            name="type",
            field=models.CharField(
                choices=[
                    ("audio", "Audio"),
                    ("video", "Video"),
                    ("image", "Image"),
                    ("text", "Text"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="relatedfile",
            name="thumbnail",
            field=main.forms.sanitized_filefield.SanitizedFileField(
                blank=True,
                null=True,
                quality=75,
                size=(800, 800),
                upload_to=main.models.related_file.default_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="relatedfile",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="File content description",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="relatedfile",
            name="file",
            field=main.forms.sanitized_filefield.SanitizedFileField(
                quality=75,
                size=[2560, 2560],
                upload_to=main.models.related_file.default_upload_to,
            ),
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "api_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "file",
                    main.forms.sanitized_filefield.SanitizedFileField(
                        quality=75,
                        size=[2560, 2560],
                        upload_to=main.models.related_file.default_upload_to,
                    ),
                ),
                (
                    "thumbnail",
                    main.forms.sanitized_filefield.SanitizedFileField(
                        blank=True,
                        null=True,
                        quality=75,
                        size=(800, 800),
                        upload_to=main.models.related_file.default_upload_to,
                    ),
                ),
                (
                    "fit",
                    models.CharField(
                        blank=True,
                        choices=[("cover", "Cover"), ("contain", "Contain")],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(editable=False, max_length=1024, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("image", "Image"),
                            ("text", "Text"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="File content description",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="relatedfile",
            name="fit",
            field=models.CharField(
                blank=True,
                choices=[("cover", "Cover"), ("contain", "Contain")],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="relatedfile",
            name="sort_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="host",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allow_outgoing_webmentions",
                    models.BooleanField(
                        default=mentions.models.mixins.mentionable._outgoing_default,
                        verbose_name="allow outgoing webmentions",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "api_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, help_text="Publicly visible"),
                ),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "color_muted",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        image_field=None,
                        max_length=25,
                        samples=[
                            ("#ee4545", "#ee4545"),
                            ("#0e70b8", "#0e70b8"),
                            ("#16b06b", "#16b06b"),
                            ("#823dae", "#823dae"),
                            ("#e13255", "#e13255"),
                            ("#fdf472", "#fdf472"),
                            ("#d86900", "#d86900"),
                            ("#636363", "#636363"),
                            ("#ff6d60", "#ff6d60"),
                            ("#f7d060", "#f7d060"),
                            ("#f3e99f", "#f3e99f"),
                            ("#98d8aa", "#98d8aa"),
                            ("#3c486b", "#3c486b"),
                            ("#f0f0f0", "#f0f0f0"),
                            ("#f9d949", "#f9d949"),
                            ("#f45050", "#f45050"),
                            ("#4d455d", "#4d455d"),
                            ("#e96479", "#e96479"),
                            ("#f5e9cf", "#f5e9cf"),
                            ("#7db9b6", "#7db9b6"),
                            ("#0a4d68", "#0a4d68"),
                            ("#088395", "#088395"),
                            ("#05bfdb", "#05bfdb"),
                            ("#00ffca", "#00ffca"),
                            ("#2c3333", "#2c3333"),
                            ("#2e4f4f", "#2e4f4f"),
                            ("#0e8388", "#0e8388"),
                            ("#cbe4de", "#cbe4de"),
                            ("#181823", "#181823"),
                            ("#537fe7", "#537fe7"),
                            ("#c0eef2", "#c0eef2"),
                            ("#e9f8f9", "#e9f8f9"),
                            ("#483838", "#483838"),
                            ("#42855b", "#42855b"),
                            ("#90b77d", "#90b77d"),
                            ("#d2d79f", "#d2d79f"),
                        ],
                    ),
                ),
                (
                    "color_vibrant",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        image_field=None,
                        max_length=25,
                        samples=[
                            ("#ee4545", "#ee4545"),
                            ("#0e70b8", "#0e70b8"),
                            ("#16b06b", "#16b06b"),
                            ("#823dae", "#823dae"),
                            ("#e13255", "#e13255"),
                            ("#fdf472", "#fdf472"),
                            ("#d86900", "#d86900"),
                            ("#636363", "#636363"),
                            ("#ff6d60", "#ff6d60"),
                            ("#f7d060", "#f7d060"),
                            ("#f3e99f", "#f3e99f"),
                            ("#98d8aa", "#98d8aa"),
                            ("#3c486b", "#3c486b"),
                            ("#f0f0f0", "#f0f0f0"),
                            ("#f9d949", "#f9d949"),
                            ("#f45050", "#f45050"),
                            ("#4d455d", "#4d455d"),
                            ("#e96479", "#e96479"),
                            ("#f5e9cf", "#f5e9cf"),
                            ("#7db9b6", "#7db9b6"),
                            ("#0a4d68", "#0a4d68"),
                            ("#088395", "#088395"),
                            ("#05bfdb", "#05bfdb"),
                            ("#00ffca", "#00ffca"),
                            ("#2c3333", "#2c3333"),
                            ("#2e4f4f", "#2e4f4f"),
                            ("#0e8388", "#0e8388"),
                            ("#cbe4de", "#cbe4de"),
                            ("#181823", "#181823"),
                            ("#537fe7", "#537fe7"),
                            ("#c0eef2", "#c0eef2"),
                            ("#e9f8f9", "#e9f8f9"),
                            ("#483838", "#483838"),
                            ("#42855b", "#42855b"),
                            ("#90b77d", "#90b77d"),
                            ("#d2d79f", "#d2d79f"),
                        ],
                    ),
                ),
                (
                    "format",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "None"), (1, "Markdown")], default=1
                    ),
                ),
                ("hero_html", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "old_slug",
                    models.SlugField(
                        editable=False, max_length=255, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("subtitle", models.CharField(blank=True, max_length=255, null=True)),
                ("preview", models.CharField(blank=True, max_length=512, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "content_html",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("content_script", models.TextField(blank=True, null=True)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "hero_image",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.uploadedfile",
                    ),
                ),
                ("hero_embedded_url", models.URLField(blank=True, null=True)),
                (
                    "preview_html",
                    models.TextField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "ordering": ("-published_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AboutPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allow_outgoing_webmentions",
                    models.BooleanField(
                        default=mentions.models.mixins.mentionable._outgoing_default,
                        verbose_name="allow outgoing webmentions",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "api_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, help_text="Publicly visible"),
                ),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "color_muted",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        image_field=None,
                        max_length=25,
                        samples=[
                            ("#ee4545", "#ee4545"),
                            ("#0e70b8", "#0e70b8"),
                            ("#16b06b", "#16b06b"),
                            ("#823dae", "#823dae"),
                            ("#e13255", "#e13255"),
                            ("#fdf472", "#fdf472"),
                            ("#d86900", "#d86900"),
                            ("#636363", "#636363"),
                            ("#ff6d60", "#ff6d60"),
                            ("#f7d060", "#f7d060"),
                            ("#f3e99f", "#f3e99f"),
                            ("#98d8aa", "#98d8aa"),
                            ("#3c486b", "#3c486b"),
                            ("#f0f0f0", "#f0f0f0"),
                            ("#f9d949", "#f9d949"),
                            ("#f45050", "#f45050"),
                            ("#4d455d", "#4d455d"),
                            ("#e96479", "#e96479"),
                            ("#f5e9cf", "#f5e9cf"),
                            ("#7db9b6", "#7db9b6"),
                            ("#0a4d68", "#0a4d68"),
                            ("#088395", "#088395"),
                            ("#05bfdb", "#05bfdb"),
                            ("#00ffca", "#00ffca"),
                            ("#2c3333", "#2c3333"),
                            ("#2e4f4f", "#2e4f4f"),
                            ("#0e8388", "#0e8388"),
                            ("#cbe4de", "#cbe4de"),
                            ("#181823", "#181823"),
                            ("#537fe7", "#537fe7"),
                            ("#c0eef2", "#c0eef2"),
                            ("#e9f8f9", "#e9f8f9"),
                            ("#483838", "#483838"),
                            ("#42855b", "#42855b"),
                            ("#90b77d", "#90b77d"),
                            ("#d2d79f", "#d2d79f"),
                        ],
                    ),
                ),
                (
                    "color_vibrant",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        image_field=None,
                        max_length=25,
                        samples=[
                            ("#ee4545", "#ee4545"),
                            ("#0e70b8", "#0e70b8"),
                            ("#16b06b", "#16b06b"),
                            ("#823dae", "#823dae"),
                            ("#e13255", "#e13255"),
                            ("#fdf472", "#fdf472"),
                            ("#d86900", "#d86900"),
                            ("#636363", "#636363"),
                            ("#ff6d60", "#ff6d60"),
                            ("#f7d060", "#f7d060"),
                            ("#f3e99f", "#f3e99f"),
                            ("#98d8aa", "#98d8aa"),
                            ("#3c486b", "#3c486b"),
                            ("#f0f0f0", "#f0f0f0"),
                            ("#f9d949", "#f9d949"),
                            ("#f45050", "#f45050"),
                            ("#4d455d", "#4d455d"),
                            ("#e96479", "#e96479"),
                            ("#f5e9cf", "#f5e9cf"),
                            ("#7db9b6", "#7db9b6"),
                            ("#0a4d68", "#0a4d68"),
                            ("#088395", "#088395"),
                            ("#05bfdb", "#05bfdb"),
                            ("#00ffca", "#00ffca"),
                            ("#2c3333", "#2c3333"),
                            ("#2e4f4f", "#2e4f4f"),
                            ("#0e8388", "#0e8388"),
                            ("#cbe4de", "#cbe4de"),
                            ("#181823", "#181823"),
                            ("#537fe7", "#537fe7"),
                            ("#c0eef2", "#c0eef2"),
                            ("#e9f8f9", "#e9f8f9"),
                            ("#483838", "#483838"),
                            ("#42855b", "#42855b"),
                            ("#90b77d", "#90b77d"),
                            ("#d2d79f", "#d2d79f"),
                        ],
                    ),
                ),
                (
                    "format",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "None"), (1, "Markdown")], default=1
                    ),
                ),
                ("hero_html", models.TextField(blank=True, null=True)),
                ("hero_embedded_url", models.URLField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "old_slug",
                    models.SlugField(
                        editable=False, max_length=255, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("subtitle", models.CharField(blank=True, max_length=255, null=True)),
                ("preview", models.CharField(blank=True, max_length=512, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "content_html",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("content_script", models.TextField(blank=True, null=True)),
                (
                    "hero_image",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.uploadedfile",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "preview_html",
                    models.TextField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "ordering": ("-published_at",),
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="messageoftheday",
            old_name="content",
            new_name="content_html",
        ),
        migrations.RenameField(
            model_name="messageoftheday",
            old_name="title",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="messageoftheday",
            name="description",
            field=models.CharField(
                blank=True, help_text="Admin only", max_length=64, null=True
            ),
        ),
        migrations.CreateModel(
            name="AppPost",
            fields=[
                (
                    "post_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.post",
                    ),
                ),
                ("codename", models.CharField(max_length=255, unique=True)),
                ("script_html", models.TextField(blank=True, null=True)),
                (
                    "script_is_widget",
                    models.BooleanField(
                        default=False,
                        help_text="If true, this app can be included as part of a parent UI. Otherwise it should only displayed as its own window.",
                    ),
                ),
                (
                    "icon",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="main.uploadedfile",
                    ),
                ),
                (
                    "repository",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_post",
                        to="github.githubrepository",
                    ),
                ),
            ],
            options={
                "ordering": ("-published_at",),
                "abstract": False,
            },
            bases=("main.post",),
        ),
        migrations.CreateModel(
            name="ChangelogPost",
            fields=[
                (
                    "post_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.post",
                    ),
                ),
                ("version", models.CharField(max_length=32)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changelogs",
                        to="main.apppost",
                    ),
                ),
            ],
            options={
                "ordering": ("-published_at",),
                "abstract": False,
            },
            bases=("main.post",),
        ),
        migrations.CreateModel(
            name="AppResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        storage=main.storage.OverwriteStorage(),
                        upload_to=main.models.posts.app.appresource_upload_to,
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="main.apppost",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="apppost",
            name="script",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="main.appresource",
            ),
        ),
        migrations.CreateModel(
            name="SiteHCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text=common.microformats.HCard["p_name"], max_length=255
                    ),
                ),
                ("url", models.URLField(help_text=common.microformats.HCard["u_url"])),
                (
                    "locality",
                    models.CharField(
                        blank=True,
                        help_text=common.microformats.HCard["p_locality"],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text=common.microformats.HCard["p_region"],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text=common.microformats.HCard["p_country_name"],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True,
                        help_text=common.microformats.HCard["dt_bday"],
                        null=True,
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        help_text=common.microformats.HCard["u_logo"],
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="main.uploadedfile",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        help_text=common.microformats.HCard["u_photo"],
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="main.uploadedfile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="link",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="link",
            name="sort_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="apppost",
            name="widget_style",
            field=models.CharField(
                blank=True,
                help_text="Element style applied to the element that wraps the embedded widget - use to apply a background or padding.",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="PointsOfInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="link",
            name="label",
            field=models.CharField(blank=True, max_length=129, null=True),
        ),
    ]
