# Generated by Django 3.2.4 on 2022-03-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial_squashed_0004_auto_20220328_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
