# Generated by Django 3.2.4 on 2022-03-30 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220330_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='accent_foreground_color',
            new_name='on_accent_color',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='foreground_color',
            new_name='on_primary_color',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='content_format',
            new_name='format',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='accent_foreground_color',
            new_name='on_accent_color',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='foreground_color',
            new_name='on_primary_color',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='content_format',
            new_name='format',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='accent_foreground_color',
            new_name='on_accent_color',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='foreground_color',
            new_name='on_primary_color',
        ),
        migrations.RenameField(
            model_name='changelog',
            old_name='content_format',
            new_name='format',
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.app'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(editable=False, max_length=7, unique=True),
        ),
    ]
