# Generated by Django 3.2.4 on 2022-04-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0004_auto_20220406_1924'),
        ('main', '0007_auto_20220401_1049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AlterField(
            model_name='app',
            name='code_languages',
            field=models.ManyToManyField(blank=True, to='github.GithubLanguage'),
        ),
    ]
