# Generated by Django 3.2.4 on 2022-04-27 17:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0010_auto_20220411_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatedfile',
            options={},
        ),
        migrations.RemoveField(
            model_name='app',
            name='links',
        ),
        migrations.RemoveField(
            model_name='host',
            name='host_type',
        ),
        migrations.RemoveField(
            model_name='host',
            name='is_source',
        ),
        migrations.RemoveField(
            model_name='host',
            name='tooltip',
        ),
        migrations.AlterField(
            model_name='article',
            name='hero_css',
            field=models.CharField(blank=True, choices=[('contain', 'contain'), ('cover', 'cover')], default='cover', help_text='space-separated CSS class names', max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview_image_css',
            field=models.CharField(blank=True, choices=[('contain', 'contain'), ('cover', 'cover')], default='cover', help_text='space-separated CSS class names', max_length=80),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('object_id', models.PositiveIntegerField()),
                ('url', models.URLField(max_length=512)),
                ('description', models.CharField(blank=True, choices=[('source', 'Source'), ('install', 'Install'), ('download', 'Download')], max_length=128, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='main.host')),
            ],
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('url', 'content_type', 'object_id'), name='unique_url_per_target'),
        ),
    ]
