# Generated by Django 4.0.4 on 2022-05-05 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0007_githublanguage_created_at'),
        ('main', '0016_alter_app_repository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='code_languages',
        ),
        migrations.AddField(
            model_name='app',
            name='primary_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='github.githublanguage'),
        ),
    ]
