# Generated by Django 4.0.4 on 2022-05-19 15:00

from django.db import migrations, models
import main.forms.filename
import main.forms.sanitized_filefield


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedfile',
            name='original_filename',
            field=models.CharField(editable=False, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=main.forms.sanitized_filefield.SanitizedFileField(quality=75, size=[2560, 1440], upload_to=main.forms.filename.RandomFilename('icon/app/', filename_attrs=[], filename_literals=[])),
        ),
        migrations.AlterField(
            model_name='article',
            name='hero_image',
            field=main.forms.sanitized_filefield.SanitizedFileField(quality=75, size=[2560, 1440], upload_to=main.forms.filename.RandomFilename('article/%Y/', filename_attrs=[], filename_literals=['hero'])),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview_image',
            field=main.forms.sanitized_filefield.SanitizedFileField(quality=75, size=[2560, 1440], upload_to=main.forms.filename.RandomFilename('article/%Y/', filename_attrs=[], filename_literals=['preview'])),
        ),
        migrations.AlterField(
            model_name='relatedfile',
            name='file',
            field=main.forms.sanitized_filefield.SanitizedFileField(quality=75, size=[2560, 1440], upload_to=main.forms.filename.RandomFilename('related/%Y/', filename_attrs=['description'], filename_literals=[])),
        ),
    ]
