# Generated by Django 4.0.4 on 2022-05-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_app_icon_alter_article_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='format',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Markdown')], default=1),
        ),
        migrations.AlterField(
            model_name='blog',
            name='format',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Markdown')], default=1),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='format',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Markdown')], default=1),
        ),
    ]
