# Generated by Django 4.1.5 on 2023-02-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_remove_app_allow_incoming_webmentions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tweet",
            field=models.BooleanField(
                default=False,
                help_text='A link to this post will be tweeted by <a href="https://twitter.com/">@</a> when you save changes.',
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="tweet",
            field=models.BooleanField(
                default=False,
                help_text='A link to this post will be tweeted by <a href="https://twitter.com/">@</a> when you save changes.',
            ),
        ),
        migrations.AlterField(
            model_name="changelog",
            name="tweet",
            field=models.BooleanField(
                default=False,
                help_text='A link to this post will be tweeted by <a href="https://twitter.com/">@</a> when you save changes.',
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="tweet",
            field=models.BooleanField(
                default=False,
                help_text='A link to this post will be tweeted by <a href="https://twitter.com/">@</a> when you save changes.',
            ),
        ),
    ]
