# Generated by Django 4.1.5 on 2023-02-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_alter_article_tweet_alter_blog_tweet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tweet",
            field=models.BooleanField(
                default=False,
                help_text="Tweet a link to this post when you save changes",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="tweet",
            field=models.BooleanField(
                default=False,
                help_text="Tweet a link to this post when you save changes",
            ),
        ),
        migrations.AlterField(
            model_name="changelog",
            name="tweet",
            field=models.BooleanField(
                default=False,
                help_text="Tweet a link to this post when you save changes",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="tweet",
            field=models.BooleanField(
                default=False,
                help_text="Tweet a link to this post when you save changes",
            ),
        ),
    ]
