# Generated by Django 4.1.5 on 2023-03-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_alter_article_tweet_alter_blog_tweet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messageoftheday",
            name="display_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="messageoftheday",
            name="display_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
