# Generated by Django 4.1.5 on 2023-03-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_messageoftheday_display_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tweet_id',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tweet_id',
        ),
        migrations.RemoveField(
            model_name='changelog',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='changelog',
            name='tweet_id',
        ),
        migrations.RemoveField(
            model_name='note',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='note',
            name='tweet_id',
        ),
    ]
