# Generated by Django 4.1.5 on 2023-03-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_article_tweet_remove_article_tweet_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='changelog',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_featured',
        ),
    ]
