# Generated by Django 4.1.5 on 2023-04-13 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_alter_app_published_at_alter_article_published_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="app",
            old_name="primary_color",
            new_name="color_muted",
        ),
        migrations.RenameField(
            model_name="app",
            old_name="on_primary_color",
            new_name="color_on_muted",
        ),
        migrations.RenameField(
            model_name="app",
            old_name="on_accent_color",
            new_name="color_on_vibrant",
        ),
        migrations.RenameField(
            model_name="app",
            old_name="accent_color",
            new_name="color_vibrant",
        ),
        migrations.RenameField(
            model_name="apptype",
            old_name="primary_color",
            new_name="color_muted",
        ),
        migrations.RenameField(
            model_name="apptype",
            old_name="on_primary_color",
            new_name="color_on_muted",
        ),
        migrations.RenameField(
            model_name="apptype",
            old_name="on_accent_color",
            new_name="color_on_vibrant",
        ),
        migrations.RenameField(
            model_name="apptype",
            old_name="accent_color",
            new_name="color_vibrant",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="primary_color",
            new_name="color_muted",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="on_primary_color",
            new_name="color_on_muted",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="on_accent_color",
            new_name="color_on_vibrant",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="accent_color",
            new_name="color_vibrant",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="primary_color",
            new_name="color_muted",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="on_primary_color",
            new_name="color_on_muted",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="on_accent_color",
            new_name="color_on_vibrant",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="accent_color",
            new_name="color_vibrant",
        ),
    ]
