# Generated by Django 4.1.5 on 2023-04-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_app_color_muted_alter_app_color_vibrant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='color_on_muted',
        ),
        migrations.RemoveField(
            model_name='app',
            name='color_on_vibrant',
        ),
        migrations.RemoveField(
            model_name='apptype',
            name='color_on_muted',
        ),
        migrations.RemoveField(
            model_name='apptype',
            name='color_on_vibrant',
        ),
        migrations.RemoveField(
            model_name='article',
            name='color_on_muted',
        ),
        migrations.RemoveField(
            model_name='article',
            name='color_on_vibrant',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='color_on_muted',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='color_on_vibrant',
        ),
    ]
