# Generated by Django 4.1.5 on 2023-04-19 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0038_remove_app_color_on_muted_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="messageoftheday",
            old_name="display_from",
            new_name="public_from",
        ),
        migrations.RenameField(
            model_name="messageoftheday",
            old_name="display_until",
            new_name="public_until",
        ),
        migrations.RenameField(
            model_name="messageoftheday",
            old_name="display",
            new_name="is_published",
        ),
        migrations.AlterField(
            model_name="messageoftheday",
            name="is_published",
            field=models.BooleanField(default=True, help_text="Publicly visible"),
        ),
        migrations.AddField(
            model_name="messageoftheday",
            name="published_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
