# Generated by Django 4.1.5 on 2023-04-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0040_themeoverride"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="themeoverride",
            options={
                "ordering": [
                    "-is_published",
                    "public_from",
                    "public_until",
                    "-created_at",
                ]
            },
        ),
    ]
