# Generated by Django 4.1.5 on 2023-08-26 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0041_alter_themeoverride_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changelog",
            name="app",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="changelogs",
                to="main.app",
            ),
        ),
    ]
