# Generated by Django 4.1.5 on 2023-08-26 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_changelog_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='main.apptype'),
        ),
    ]
