# Generated by Django 4.1.5 on 2023-08-27 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_app_app_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'ordering': ['-published_at']},
        ),
    ]
