# Generated by Django 4.2.5 on 2023-09-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_app_color_muted_alter_app_color_vibrant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.CharField(blank=True, choices=[('source', 'Source'), ('install', 'Install'), ('download', 'Download'), ('webapp', 'Webapp'), ('link', 'Link')], max_length=128, null=True),
        ),
    ]
