# Generated by Django 4.2.5 on 2023-11-28 13:41
import uuid

from django.db import migrations


def generate_uuid(apps, schema_editor):
    affected_models = ["article", "blog", "changelog", "note", "relatedfile"]
    for m in affected_models:
        Model = apps.get_model("main", m)
        for row in Model.objects.all():
            row.api_id = uuid.uuid4()
            row.save(update_fields=["api_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0047_apieditable_webpost_and_relatedfile"),
    ]

    operations = [
        migrations.RunPython(generate_uuid, reverse_code=migrations.RunPython.noop)
    ]
