# Generated by Django 4.2.5 on 2023-12-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_apieditable_20231128_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedfile',
            name='description',
            field=models.CharField(blank=True, default='', help_text='File content description', max_length=140),
        ),
    ]
