# Generated by Django 4.2.5 on 2024-03-01 14:03

import main.forms.filename
import main.forms.sanitized_filefield
import main.models.webapp
import main.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0053_webapp_resource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webappresource",
            name="file",
            field=models.FileField(
                storage=main.storage.OverwriteStorage(),
                upload_to=main.models.webapp._resource_upload_to,
            ),
        ),
    ]
