# Generated by Django 4.2.5 on 2024-03-01 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0055_alter_article_hero_image_alter_relatedfile_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webapp",
            options={},
        ),
        migrations.AlterModelOptions(
            name="webappresource",
            options={},
        ),
        migrations.RenameField(
            model_name="webapp",
            old_name="script",
            new_name="file",
        ),
    ]
