# Generated by Django 5.0.3 on 2024-04-23 10:34

import main.forms.filename
import main.forms.sanitized_filefield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_webapp_options_alter_webappresource_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedfile',
            name='file',
            field=main.forms.sanitized_filefield.SanitizedFileField(quality=75, size=[2560, 2560], upload_to=main.forms.filename.RandomFilename('related/%Y/', filename_attrs=['description'], filename_literals=[])),
        ),
    ]
