# Generated by Django 5.1.1 on 2024-09-17 13:06

import uuid

from django.db import migrations, models


def _generate_uuid(apps, schema_editor):
    App = apps.get_model("main", "App")
    for row in App.objects.all():
        row.api_id = uuid.uuid4()
        row.save(update_fields=["api_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0058_relatedfile_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="app",
            old_name="description",
            new_name="content",
        ),
        migrations.AlterField(
            model_name="app",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="app",
            name="content_html",
            field=models.TextField(blank=True, default="", editable=False),
        ),
        migrations.AddField(
            model_name="app",
            name="api_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(_generate_uuid),
        migrations.AlterField(
            model_name="app",
            name="api_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
