# Generated by Django 5.1.7 on 2025-03-14 12:00

import uuid

import colorfield.fields
import django.db.models.deletion
import django.utils.timezone
import main.forms.sanitized_filefield
import main.models.related_file
import mentions.models.mixins.mentionable
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0060_app_format"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="relatedfile",
            name="fit",
            field=models.CharField(
                blank=True,
                choices=[("cover", "Cover"), ("contain", "Container")],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="relatedfile",
            name="thumbnail",
            field=main.forms.sanitized_filefield.SanitizedFileField(
                blank=True,
                null=True,
                quality=75,
                size=(800, 800),
                upload_to=main.models.related_file.default_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="relatedfile",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="File content description",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="relatedfile",
            name="file",
            field=main.forms.sanitized_filefield.SanitizedFileField(
                quality=75,
                size=[2560, 2560],
                upload_to=main.models.related_file.default_upload_to,
            ),
        ),
    ]
