# Generated by Django 5.1.7 on 2025-03-13 15:00

import main.forms.filename
import main.forms.sanitized_filefield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0060_app_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatedfile",
            name="fit",
            field=models.CharField(
                blank=True,
                choices=[("cover", "Cover"), ("contain", "Container")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="relatedfile",
            name="thumbnail",
            field=main.forms.sanitized_filefield.SanitizedFileField(
                blank=True,
                null=True,
                quality=75,
                size=(800, 800),
                upload_to=main.forms.filename.RandomFilename(
                    "related/%Y/",
                    filename_attrs=["description"],
                    filename_literals=["thumb"],
                ),
            ),
        ),
    ]
