# Generated by Django 5.1.7 on 2025-04-24 10:37

import common.microformats
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0062_0076_squashed_posts_remake"),
    ]

    operations = [
        migrations.DeleteModel(name="sitehcard"),
        migrations.CreateModel(
            name="SiteHCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text=common.microformats.HCard["p_name"], max_length=255
                    ),
                ),
                ("url", models.URLField(help_text=common.microformats.HCard["u_url"])),
                (
                    "locality",
                    models.CharField(
                        blank=True,
                        help_text=common.microformats.HCard["p_locality"],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text=common.microformats.HCard["p_region"],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text=common.microformats.HCard["p_country_name"],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True,
                        help_text=common.microformats.HCard["dt_bday"],
                        null=True,
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        help_text=common.microformats.HCard["u_logo"],
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="main.uploadedfile",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        help_text=common.microformats.HCard["u_photo"],
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="main.uploadedfile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
