# Generated by Django 5.1.7 on 2025-03-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0062_uploadedfile_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="old_slug",
            field=models.SlugField(
                editable=False, max_length=255, null=True, unique=True
            ),
        ),
    ]
