# Generated by Django 5.1.7 on 2025-04-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0063_remake_sitehcard"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="link",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="link",
            name="sort_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
