# Generated by Django 5.1.7 on 2025-03-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0063_alter_post_old_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatedfile",
            name="fit",
            field=models.CharField(
                blank=True,
                choices=[("cover", "Cover"), ("contain", "Contain")],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="fit",
            field=models.CharField(
                blank=True,
                choices=[("cover", "Cover"), ("contain", "Contain")],
                max_length=32,
                null=True,
            ),
        ),
    ]
