# Generated by Django 5.1.7 on 2025-03-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0064_alter_relatedfile_fit_alter_uploadedfile_fit"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatedfile",
            name="sort_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
