# Generated by Django 5.1.7 on 2025-04-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0064_alter_link_options_link_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="apppost",
            name="widget_style",
            field=models.CharField(
                blank=True,
                help_text="Element style applied to the element that wraps the embedded widget - use to apply a background or padding.",
                max_length=1024,
                null=True,
            ),
        ),
    ]
