# Generated by Django 5.1.7 on 2025-03-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0065_relatedfile_sort_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
