# Generated by Django 5.2 on 2025-05-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0065_apppost_widget_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpost",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
