# Generated by Django 5.2 on 2025-05-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0066_editable_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="preview_text",
            new_name="preview",
        ),
        migrations.AlterField(
            model_name="post",
            name="preview",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="preview_html",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.RenameField(
            model_name="aboutpost",
            old_name="preview_text",
            new_name="preview",
        ),
        migrations.AlterField(
            model_name="aboutpost",
            name="preview",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="aboutpost",
            name="preview_html",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
