# Generated by Django 5.1.7 on 2025-03-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0067_alter_app_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dev", "Dev"),
                    ("test", "Test"),
                    ("published", "Public"),
                    ("deprecated", "Deprecated"),
                ],
                default="dev",
                max_length=16,
                null=True,
            ),
        ),
    ]
