# Generated by Django 5.2 on 2025-05-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0067_preview_formatting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpost",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
