# Generated by Django 5.1.7 on 2025-03-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0069_remove_post_app_apppost_appresource_apppost_script_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apppost",
            name="hero_embedded_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="changelogpost",
            name="hero_embedded_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="hero_embedded_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
