# Generated by Django 5.2 on 2025-05-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0069_pointsofinterest"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="label",
            field=models.CharField(blank=True, max_length=129, null=True),
        ),
    ]
