# Generated by Django 5.2 on 2025-05-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0070_link_label"),
    ]

    operations = [
        migrations.DeleteModel(
            name="About",
        ),
        migrations.RemoveField(
            model_name="app",
            name="app_type",
        ),
        migrations.RemoveField(
            model_name="app",
            name="primary_language",
        ),
        migrations.RemoveField(
            model_name="app",
            name="project",
        ),
        migrations.RemoveField(
            model_name="app",
            name="repository",
        ),
        migrations.RemoveField(
            model_name="app",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="article",
            name="apps",
        ),
        migrations.RemoveField(
            model_name="changelog",
            name="app",
        ),
        migrations.RemoveField(
            model_name="article",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="changelog",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="note",
            name="tags",
        ),
        migrations.DeleteModel(
            name="AppType",
        ),
        migrations.DeleteModel(
            name="App",
        ),
        migrations.DeleteModel(
            name="Article",
        ),
        migrations.DeleteModel(
            name="Blog",
        ),
        migrations.DeleteModel(
            name="Changelog",
        ),
        migrations.DeleteModel(
            name="Note",
        ),
    ]
