# Generated by Django 5.1.7 on 2025-04-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0070_apppost_hero_embedded_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apppost",
            name="script_html",
            field=models.TextField(blank=True, null=True),
        ),
    ]
