# Generated by Django 5.1.7 on 2025-04-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0071_apppost_script_html"),
    ]

    operations = [
        migrations.AddField(
            model_name="apppost",
            name="script_is_widget",
            field=models.BooleanField(
                default=False,
                help_text="If true, this app can be included as part of a parent UI. Otherwise it should only displayed as its own window.",
            ),
        ),
    ]
