# Generated by Django 5.2 on 2025-05-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0071_delete_about_remove_app_app_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Project",
        ),
    ]
