# Generated by Django 5.2 on 2025-05-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0072_delete_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webappresource",
            name="webapp",
        ),
        migrations.DeleteModel(
            name="WebApp",
        ),
        migrations.DeleteModel(
            name="WebappResource",
        ),
    ]
