# Generated by Django 5.1.7 on 2025-04-15 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0073_aboutpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteHCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("html", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
