# Generated by Django 5.1.7 on 2025-04-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0074_sitehcard"),
    ]

    operations = [
        migrations.RenameField(
            model_name="messageoftheday",
            old_name="content",
            new_name="content_html",
        ),
        migrations.RenameField(
            model_name="messageoftheday", old_name="title", new_name="description"
        ),
        migrations.AlterField(
            model_name="messageoftheday",
            name="description",
            field=models.CharField(
                blank=True, help_text="Admin only", max_length=64, null=True
            ),
        ),
    ]
