# Generated by Django 5.2 on 2025-05-14 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0074_feed_post_feeds"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feed",
            options={"ordering": ("-published_at",)},
        ),
        migrations.AddField(
            model_name="feed",
            name="is_published",
            field=models.BooleanField(default=True, help_text="Publicly visible"),
        ),
        migrations.AddField(
            model_name="feed",
            name="published_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
