# Generated by Django 5.2 on 2025-05-19 09:55

from django.db import migrations, models


def apply_default_ordering(apps, schema_editor):
    for model_name in ["Feed", "RelatedFile", "Link"]:
        Model = apps.get_model("main", model_name)
        for order, item in enumerate(Model.objects.all(), 1):
            item.sort_order = order
            item.save(update_fields=["sort_order"])


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0075_alter_feed_options_feed_is_published_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feed",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AlterModelOptions(
            name="relatedfile",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="feed",
            name="sort_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="link",
            name="sort_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="relatedfile",
            name="sort_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="feeds",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="main.feed"
            ),
        ),
        migrations.RunPython(
            code=apply_default_ordering, reverse_code=migrations.RunPython.noop
        ),
    ]
