# Generated by Django 5.1.7 on 2025-04-16 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github", "0014_alter_cachedresponse_data"),
        ("main", "0075_rename_content_messageoftheday_content_html_and_more"),
    ]

    operations = [
        migrations.DeleteModel("changelogpost"),
        migrations.DeleteModel("apppost"),
        migrations.CreateModel(
            name="AppPost",
            fields=[
                (
                    "post_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.post",
                    ),
                ),
                ("codename", models.CharField(max_length=255, unique=True)),
                ("script_html", models.TextField(blank=True, null=True)),
                (
                    "script_is_widget",
                    models.BooleanField(
                        default=False,
                        help_text="If true, this app can be included as part of a parent UI. Otherwise it should only displayed as its own window.",
                    ),
                ),
                (
                    "icon",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="main.uploadedfile",
                    ),
                ),
                (
                    "repository",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_post",
                        to="github.githubrepository",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="main.appresource",
                    ),
                ),
            ],
            options={
                "ordering": ("-published_at",),
                "abstract": False,
            },
            bases=("main.post",),
        ),
        migrations.CreateModel(
            name="ChangelogPost",
            fields=[
                (
                    "post_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.post",
                    ),
                ),
                ("version", models.CharField(max_length=32)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changelogs",
                        to="main.apppost",
                    ),
                ),
            ],
            options={
                "ordering": ("-published_at",),
                "abstract": False,
            },
            bases=("main.post",),
        ),
    ]
