# Generated by Django 5.2.1 on 2025-05-20 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0076_alter_feed_options_alter_relatedfile_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutpost",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="aboutpost",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                related_query_name="child",
                to="main.aboutpost",
            ),
        ),
        migrations.AddField(
            model_name="aboutpost",
            name="path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="aboutpost",
            name="sort_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
