# Generated by Django 5.2.1 on 2025-05-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0078_initialize_about_sort_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpost",
            name="path",
            field=models.CharField(default="", editable=False, max_length=255),
        ),
    ]
