# Generated by Django 5.2.1 on 2025-09-29 09:40

import main.models.posts.app
import main.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0079_alter_aboutpost_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appresource",
            name="file",
            field=models.FileField(
                max_length=255,
                storage=main.storage.OverwriteStorage(),
                upload_to=main.models.posts.app.appresource_upload_to,
            ),
        ),
    ]
