# Generated by Django 5.2.1 on 2025-09-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0080_alter_appresource_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="apppost",
            name="widget_data",
            field=models.CharField(
                blank=True,
                help_text="Optional data passed to widget via URL search params.",
                max_length=1024,
                null=True,
            ),
        ),
    ]
