# Generated by Django 6.0.1 on 2026-02-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_apppost_widget_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='slug',
            field=models.SlugField(max_length=64, unique=True),
        ),
    ]
