# Generated by Django 6.0.1 on 2026-04-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0082_feed_description_alter_feed_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatedfile",
            name="is_nsfw",
            field=models.BooleanField(
                default=False,
                help_text="If true, require user action to render this file.",
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="is_nsfw",
            field=models.BooleanField(
                default=False,
                help_text="If true, require user action to render this file.",
            ),
        ),
    ]
