# Generated by Django 6.0.4 on 2026-05-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0083_relatedfile_is_nsfw_uploadedfile_is_nsfw"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatedfile",
            name="is_preview_allowed",
            field=models.BooleanField(
                default=True,
                help_text="If false, this file should be excluded from preview UIs.",
            ),
        ),
        migrations.AddField(
            model_name="relatedfile",
            name="is_standalone",
            field=models.BooleanField(
                default=False,
                help_text="If true, this file should not be grouped for viewing with other files - it will be rendered or otherwise linked to in some custom manner.",
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="is_preview_allowed",
            field=models.BooleanField(
                default=True,
                help_text="If false, this file should be excluded from preview UIs.",
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="is_standalone",
            field=models.BooleanField(
                default=False,
                help_text="If true, this file should not be grouped for viewing with other files - it will be rendered or otherwise linked to in some custom manner.",
            ),
        ),
    ]
