# Generated by Django 6.0.4 on 2026-05-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0084_relatedfile_is_preview_allowed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatedfile",
            name="aspect_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="relatedfile",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relatedfile",
            name="height",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relatedfile",
            name="width",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="aspect_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="height",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="width",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
