# Generated by Django 4.1.5 on 2023-04-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bma_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
